### ISSUE TITLE
Error: node-v64 missing from release v4.2.1

### ISSUE THREAD

**Issue by jdaltonchilders** [atom/node-keytar#103]
While testing Node Version 10.1.0 and Node-Sass Version 4.9.0, I get the following error:

`
prebuild-install info begin Prebuild-install version 2.5.1
prebuild-install info looking for local prebuild @ prebuilds\keytar-v4.2.1-node-v64-win32-x64.tar.gz
prebuild-install info looking for cached prebuild @ C:\Users\_<username_removed>_\AppData\Roaming\npm-cache\_prebuilds\https-github.com-atom-node-keytar-releases-download-v4.2.1-keytar-v4.2.1-node-v64-win32-x64.tar.gz
prebuild-install http request GET https://github.com/atom/node-keytar/releases/download/v4.2.1/keytar-v4.2.1-node-v64-win32-x64.tar.gz
prebuild-install http 404 https://github.com/atom/node-keytar/releases/download/v4.2.1/keytar-v4.2.1-node-v64-win32-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=10.1.0 runtime=node arch=x64 platform=win32)
`

Looking at the v4.2.1 release I don't see a node-v64.

**Comment by shiftkey** [comment]
This has been fixed in #126 and is available in `4.3.0`
