### ISSUE TITLE
Please modify readme to include usage

### ISSUE THREAD

**Issue by yaizudamashii** [atom/node-keytar#107]
Please provide example code in readme to instruct us on how to use keytar.  

I'm doing the following
```
const keytar = require('keytar');
....
keytar.setPassword('service', 'account', 'password');
...
let password = keytar.getPassword('service', 'account');

```
but password is 
`Promise { <pending> }`
obviously,
`password.next(); `
gives an error

How do I get the actual password?

**Comment by yaizudamashii** [comment]
Ok so I guess you have to call the resulting promise.  But I think it would be good to include in readme.
let password = keytar.getPassword('service', 'account');
password.then((result) => {
  //result is 'password'
});

**Comment by shiftkey** [comment]
@yaizudamashii this does get a mention in the README, but could definitely be emphasized:

> Every function in keytar is asynchronous and returns a promise.

Feel free to submit a PR to add an example snippet that would help make this more explicit.
