### ISSUE TITLE
Do not double-pack release assets

### ISSUE THREAD

**Issue by TomasHubelbauer** [atom/node-keytar#108]
This is kinda in a reference to #106 where I had to untar things twice, but also just generally. Why have the assets be `.tar.gz` and then in another `.tar` and with further relative path before one gets to the `.node` file?

Would it be possible to instead just publish the `.node` files and instead of calling them just `keytar.node` have them have the full name like the asset archive file names currently are?

**Comment by shiftkey** [comment]
@TomasHubelbauer this is the output from [`prebuild`](https://www.npmjs.com/package/prebuild) and we use it's related project `prebuild-install` to install the appropriate dependency version (if applicable) at `npm install` time. 

I couldn't find an upstream discussion about this archiving format, but I think https://github.com/prebuild/prebuild is the place to raise this, so I'm going to close it out as external to `node-keytar`.
