### ISSUE TITLE
Error: The stub received bad data

### ISSUE THREAD

**Issue by jaykumarthaker** [atom/node-keytar#112]
When storing password (JWT token in my case) having characters greater than 2500 throws below error. Though it works fine if the characters are less than 2500. Is there any max. length that we have to take care of as well?
```

(node:16068) UnhandledPromiseRejectionWarning: Error: The stub received bad data.

(node:16068) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16068) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code. 
```

**Comment by shiftkey** [comment]
@jaykumarthaker were you running this on Windows? I did a cursory Google search for that error message and that seemed to be the right OS, so I put together an example (on Windows `10.0.17763.253`) with Node 11:

```js
const keytar = require('keytar')

const service = 'whatever'
const account = 'also-whatever'
const password = 'x'.repeat(2500)

keytar.setPassword(service, account, password).then(() => {
    console.log(`completed`)
}, error => {
    console.error(error)
})
```

At 2500 characters this reported `completed`, and so I tweaked it to `2600` and that triggered the error. 

This feels like an OS constraint and I'm not sure we can fix this in `keytar`, so I'm going to close it out. Let me know if there's anything else to add.
