### ISSUE TITLE
Sometimes, it lost the password

### ISSUE THREAD

**Issue by KrzysZG37** [atom/node-keytar#120]
Key-tar version: 4.1.0
System: Mac OS X 10.13.6

I struggle with loosing the saved password. Unfortunately, it occurs randomly, sometimes after 5th application launch, sometimes after 15th one.

**Comment by shiftkey** [comment]
@KrzysZG37 It's hard to say what's happening without any context:

 - Can you share an example of how you are using keytar that fails sometimes?
 - Are there any errors that occur when trying to read the value? 
 - Is the value still present in the keychain after the error is raised?

**Comment by KrzysZG37** [comment]
@shiftkey  This is my method for request saved password
```
var credentialsPromise = keytar.getPassword('APP_NAME', account);
       credentialsPromise.then(
    (result) => {
      action.call(this, result, account);
    },
    (err) => {
      log.error(err);
    }
  );
```

The problem is, that sometimes the promise just returns null value. It looks like, saved credentials are erased from the Mac keychain in the unexpected way.

**Comment by fangzhzh** [comment]
@KrzysZG37 I think I encountered the same problem, in our production, our uses randomly get empty password from keytar.getPassword

**Comment by julianhille** [comment]
I can confirm something like this on windows.
Starting the app through windows autostart and logging all the values from keytar out:
Autostart:
- first call to get the keys we get for all 3 values: null
- second call we get a buffer and two times null

Stop app and restart it:
- all values are filled

**Comment by connormakh** [comment]
I've been experiencing the same issue on windows, keytar randomly gives me null values sometimes.

**Comment by RMacfarlane** [comment]
I've run into this on MacOS, my problem was that I have several processes that may read and write to the keychain simultaneously. Currently on mac, writing to the keychain is not atomic, if the item exists it deletes it and adds it again:
https://github.com/atom/node-keytar/blob/master/src/keytar_mac.cc#L81-L99

So with unlucky timing I read just after the item has been deleted. I believe https://developer.apple.com/documentation/security/1399963-seckeychainitemmodifyattributesa could be used to do the update instead.
