### ISSUE TITLE
Can not get password with node-pkg generated binary

### ISSUE THREAD

**Issue by fuchanglin** [atom/node-keytar#121]
Hi, there,
    I am trying to package my app with node-keytar using https://www.npmjs.com/package/pkg, everything works great when I run the js with node.
However after packaging to binary, even though `keytar.setPassword(serviceName, accountName, password)` works fine,`keytar.getPassword(serviceName, accountName);` always gives me the following error: `The user name or passphrase you entered is not correct.`
    Any idea how to fix this ?

Environment: macOS High Sierra v10.13.6, node v8.11.3, pkg v4.3.3, node-keytar v4.2.1

**Comment by fuchanglin** [comment]
Hi, @shiftkey ,
    Thanks for the quick response. I tried (lock/unlock) before I posted the issue, it is actually same result on my computer. 
    I think I may found the cause of my issue, I run node raw_app.js to set password, but use packaged binary to get the password, the weird thing is using the binary cmd, I can also set the password, but can not get the password. I don't know what is the security limitation of macos here.

**Comment by mo5h** [comment]
I'm getting the same issue, I also seem to be able to set passwords but not retrieve them, running linux 
node v10.6.0, Ubuntu 18.04.1 LTS, keytar v4.2.1

**Comment by shiftkey** [comment]
>  I don't know what is the security limitation of macos here.

I'm not sure of the issue here either, so I'm going to close this out as I think this is outside the scope of what `node-keytar` can control.
