### ISSUE TITLE
Windows Credential Vault: CRED_PERSIST_ENTERPRISE possible?

### ISSUE THREAD

**Issue by jakobvogel** [atom/node-keytar#122]
Hello & many thanks for providing `keytar`! I am currently working on a project that needs to run in a Windows Enterprise environment where passwords should be roamed for a user. Currently, local password storage is hardwired:

https://github.com/atom/node-keytar/blob/e48b67dd7f0ab409e982559a01d07e30bb5bb30a/src/keytar_win.cc#L136

Would it be possible to change this to `CRED_PERSIST_ENTERPRISE` as described [here](https://docs.microsoft.com/en-us/windows/desktop/api/wincred/ns-wincred-_credentiala)? If I understand things correctly, this should lead to passwords being shared for a single user across an enterprise network.

**Comment by shiftkey** [comment]
@jakobvogel that line of code was added in all the way back in #2 - which was changing the behaviour from encrypted files on disk to using the credential storage.

Feel free to open a PR and I'll see if I can get some :eyes: on it from the relevant reviewers to get their feeling on it, as I don't have much else context to go from currently.

**Comment by jakobvogel** [comment]
@shiftkey thanks for your quick reaction. The PR is ready for review.
