### ISSUE TITLE
Why Error: An invalid record was encountered while using keytar.setPassword()

### ISSUE THREAD

**Issue by shaluyadav13** [atom/node-keytar#124]
While using keytar.setPassword() function few times I get Error: An invalid record was encountered. Not understanding what the issue is. 

`await keytar.setPassword(kService, kAccount, JSON.stringify(cookie));`

Any help will be appreciated.

**Comment by shiftkey** [comment]
This appears to be an error coming from Keychain itself: https://discussions.apple.com/thread/5140587

I'm not sure what `keytar` itself can do aside from surface the error and require the caller to handle it.
