### ISSUE TITLE
Incompatibility with JNKeychain

### ISSUE THREAD

**Issue by idoodler** [atom/node-keytar#130]
I am working on converting a Cordova project to an Electron project. The project used JNKeychain to save credentials to the macOS Keychain.

JNKeychain happens to save credentials via `[NSKeyedArchiver archivedDataWithRootObject:]` which results in a `bplist` (Binary Plist) in the Keychain. I am unable to read and interpret the data with `simple-plist` which supports `bplist` files.

Can anyone point me in the right direction on how to interpret the `bplist` data and convert it into JSON?

Thanks

**Comment by shiftkey** [comment]
I'm not familiar with using `bplist` and unfortunately cannot help. Maybe one of the other `plist`-parsing projects knows more about this.

**Comment by idoodler** [comment]
@shiftkey An option for getting binary data would fix this issue. `node-keytar` only returns UTF-8 data.
