### ISSUE TITLE
I have a problem. I always see confirmation popup on Mac OS (Electron 3) about access to Keychain even if I select Allow always. Is there any workaround for this?

### ISSUE THREAD

**Issue by victorious85** [atom/node-keytar#135]
I have a problem. I always see confirmation popup on Mac OS (Electron 3) about access to Keychain even if I select Allow always. Is there any workaround for this?

**Comment by Strori** [comment]
I have same problem.

**Comment by dmitrykurochka** [comment]
Waiting to get workaround too

**Comment by shiftkey** [comment]
It's not clear to me which version of `keytar` anyone is running here (or the specific build of Electron). Can you add more details?

**Comment by dmitrykurochka** [comment]
The latest one

**Comment by victorious85** [comment]
"keytar": "^4.3.0",

keytar
    .getPassword(' key', userId)
    .then(result => {
      event.returnValue = result;
      return Promise.resolve(true);
    })
    .catch(error => console.log('error: ', error));


This caused user prompt to allow using keychain every time. It would be very annoying for user. Have you faced the same issue?

**Comment by shiftkey** [comment]
> Have you faced the same issue? 

I believe this issue is related to building and running an Electron app without codesigning (which often happens when developing locally), and the OS asks you to allow the app to access the keychain.

**Comment by victorious85** [comment]
We have signed application and received the same result. Our application is not sandboxed. Could this cause this kind of issues?

**Comment by victorious85** [comment]
1.   "electron": "^3.0.2",  "electron-builder": "^20.28.4"
we started to use keytar only now and don't know if it worked with Electron 2.x 
2.  All is valid
3. It asks while application works without rebuilding.

**Comment by victorious85** [comment]
I found a solution to my problem.
If you set a password from the main process and then attempt to get it from a renderer process, it’ll prompt a permissions dialog for the user.
Thanks you.

**Comment by aguynamedben** [comment]
If anybody finds this much later like I did... I had a similar issue upgrading to Electron 6 because I was doing keytar get/sets from the renderer process, and between Electron 5 and Electron 6 the Electron renderer process changes names, i.e. from "Electron Helper" to "Electron Helper (Renderer)". The name change trigger macOS to re-ask for permission for every single keytar.get.

More details here: https://github.com/atom/node-keytar/issues/250
