### ISSUE TITLE
Is there a limit on password length?

### ISSUE THREAD

**Issue by aguynamedben** [atom/node-keytar#140]
What's the character limit of the password string?

I have an object representing OAuth 2 token data (i.e. accessToken, refreshToken, expiresIn, etc.) and I'd like like to store this small object securely in keytar. Can I `JSON.stringify` a small object and expect the resulting string to work as a password value in keytar? The size of the string would be limited as it's a known structure.

Or is there another recommended way of storing small objects securely?

**Comment by shiftkey** [comment]
The only limitation I've currently hit upon was in #112, and that was on Windows (~2600 characters). 

Basically we're at the mercy of the underlying OS. I haven't had a chance to test on other platforms but you can see my harness in that issue if you want to explore this further.

**Comment by aguynamedben** [comment]
Thanks for the info. I went ahead and used `JSON.stringify` in my app for a small 4-5 key object and it seems to be working fine, so any potential limit is at least above a few hundred characters, which suits my usage.
