### ISSUE TITLE
getPassword() returned Error: UNIX[No such file or directory] 

### ISSUE THREAD

**Issue by reachhary** [atom/node-keytar#147]
getPassword() API returned the following error Error: UNIX[No such file or directory] when trying to fetch credentials after an app update.

**Comment by shiftkey** [comment]
@reachhary thanks for the report.

I'm pretty sure this is an issue with Keychain Access that `keytar` cannot resolve by itself. Are you able to check that you can access the `login` keychain, where your app is trying to add it's credentials? 

This thread talks about diagnosing the same error you're seeing: https://discussions.apple.com/thread/6355363

**Comment by shiftkey** [comment]
Closing this out as an issue external to `keytar`
