### ISSUE TITLE
node-gyp rebuild FAILS with node-v8.15.0

### ISSUE THREAD

**Issue by KnockKnockNe0** [atom/node-keytar#148]
OS: Ubuntu 16.04 (xenial)
node-v8.15.0
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! Failed at the keytar@4.3.0 install script 'prebuild-install || node-gyp rebuild'.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild-install || node-gyp rebuild

**Comment by shiftkey** [comment]
@KnockKnockNe0 it's not clear to me why it failed (some missing dependency?). I'm able to build on Ubuntu 18.04 with Node 8.15.

**Comment by KnockKnockNe0** [comment]
OK i got it 'node' was missing so i linked it to 'nodejs'

`$ ln -s /usr/bin/nodejs /usr/bin/node`

then i got this:

```
Package 'gnome-keyring-1', required by 'world', not found
gyp: Call to 'pkg-config --libs-only-l gnome-keyring-1' returned exit status 1 while in binding.gyp. while trying to load binding.gyp

```
this fixed it:
```
$ apt install libgnome-keyring-dev
$ pkg-config --libs-only-l gnome-keyring-1
-lgnome-keyring -lglib-2.0  

```
