### ISSUE TITLE
Not working with Electron 4.0.1 on Windows

### ISSUE THREAD

**Issue by emusgrave** [atom/node-keytar#149]
Using Electron 4.0.1, Keytar 4.3.0, Windows 10.

Starting from electron-quick-start, adding keytar, and calling
```
keytar.getPassword('_mytokens_', '_myusername_')
    .then(password => console.log('Password is ', password));
```
Results in `errno 3228369023`

I've tried pulling keytar from master and rebuilding, since there are some recent commits that attempt to address Electron 4 compatibility, but I still get the same error.

If I downgrade to Electron 3.1.1 then it works as expected.

**Comment by emusgrave** [comment]
@dcpesses To get past the keytar.node not found error, try adding `electron-rebuild` to your project as a dev dependency, and then running an npm script with `electron-rebuild -f -w keytar`. That will rebuild the keytar.node file with whatever version of electron that you are using.

If you can get past that error, I'll be interested to hear if you have the issue that I'm having with Electron 4.0.1.

**Comment by dcpesses** [comment]
@emusgrave Actually I tried that same command with `electron-rebuild` but never could get it to actually rebuild. After executing `electron-rebuild -f -w keytar`, it would pause for 3 seconds, then display `Rebuild Complete`.  The only thing that really worked for me was running an npm script with `electron-builder install-app-deps`. It only works locally though, so as soon as I attempt to build a package for production, I get the same errors.

What _might_ work, is forking the repo and removing `prebuild-install` from the npm script `install`, as I have a sneaking suspicion the install defaults to using any available prebuilds, which are likely to fail due to issues with the same ABI used for both v3 and v4 of Electron. (See [#node-abi/54](https://github.com/lgeiger/node-abi/issues/54) for details.)

**Comment by the-duck** [comment]
This seems to be a widespread bug. I got the same issue running on a mac with keytar version 4.3.0 and electron 4.0.1, but downgrading to electron 3.1.1 worked for me...

**Comment by conteit** [comment]
Not working with electron >=4.0.0 both on macOs Mojave and Windows 10 1803

**Comment by shiftkey** [comment]
I think we need to wait on https://github.com/lgeiger/node-abi/pull/55 because of changes to ABI compatibility and how Electron 4 is built.

**Comment by shiftkey** [comment]
Closing this out in favour of the earlier report #133. I'll update that issue to make it clearer it's a broad problem.

**Comment by emusgrave** [comment]
@shiftkey Thanks for pointing me towards that issue, but I still don't think the title of that issue captures the depth of the problem. Electron 4 is the mainline release now, and as it stands today, I can't figure out any way to get keytar to work with it, manually or otherwise. 

Until this is solved, you may even want a banner on the readme that explains that this library cannot be used with Electron 4. The goal is simply to save people time. I burned a few hours trying to figure this out before just downgrading to Electron 3.

**Comment by shiftkey** [comment]
> Electron 4 is the mainline release now, and as it stands today, I can't figure out any way to get keytar to work with it, manually or otherwise.

I have an test build of GitHub Desktop that works with Electron 4 and the latest `keytar`, but th setup .

> Until this is solved, you may even want a banner on the readme that explains that this library cannot be used with Electron 4. 

Want to open a PR with some words to kick this off?

**Comment by shiftkey** [comment]
@emusgrave 

> Electron 4 is the mainline release now, and as it stands today, I can't figure out any way to get keytar to work with it, manually or otherwise.

I've got a test build running on Electron `4.0.1` but after poking at the keytar interactions it looks like it's silently failing on my side. I still need to upgrade from Electron 2.0.x first to 3.x before I can really think about digging into this (Node ABI issues aside).

> Until this is solved, you may even want a banner on the readme that explains that this library cannot be used with Electron 4. 

Want to open a PR and start this off? I'm happy to review and get something up asap.

**Comment by vladimiry** [comment]
> Until this is solved, you may even want a banner on the readme that explains that this library cannot be used with Electron 4.

This is not true. I successfully use `keytar` with electron@v4 here https://github.com/vladimiry/email-securely-app. Just don't rely on prebuilds (I simply remove the prebuilds and trigger building from sources).

**Comment by adeperio** [comment]
getting this same issue @vladimiry , any idea how I can build from source? Will this work building windows packages on a mac?

**Comment by vladimiry** [comment]
@adeperio make sure you use the latest `keytar` release as the issue with prebuilds has already been resolved.

**Comment by adeperio** [comment]
@vladimiry oh ok. I think I'm already pointing to the latest keytar (4.4.0?) and I'm still getting this problem. I'm building with electron-builder (trying to build a win 64 exe on a mac) with the following build config:

```
"npmRebuild": true,
"buildDependenciesFromSource": true
```

Is there anything else I could be doing?

**Comment by vladimiry** [comment]
Try this way:
- Remove `./node_modules/keytar/prebuilds` and `./node_modules/keytar/build` if any.
- Remove/comment-out `"npmRebuild": true,` and `"buildDependenciesFromSource": true` from your config.
- Execute `npx electron-builder install-app-deps --arch=x64` (I'm assuming you build for x64 arch running x64 system).

> Will this work building windows packages on a mac?

It's unlikely that you will be able to compile native modules for windows on mac. Native modules need to be compiled on respective platforms (win/mac/linux), for example using Appveyor and Travi CI.

**Comment by adeperio** [comment]
@vladimiry I think that's where I have been heading down the wrong direction. I was on Electron 1.8.6 and have been using prebuilds successfully to build Windows on a mac machine. But in the upgrade to Electron 4.0.4, I lost this ability with node-hid, another native dep. node-hid only supported up to Electron < 2.0 I think and still don't have prebuilds for the latest electron. 

This may not be a keytar issue and may actually be a problem with node-hid. In the mix up, I think I was rebuilding ALL native dependencies. But maybe I can use your instructions on the node-hid library first, and revert back to using the prebuilds with keytar? Thanks for sending those through. I'll report back and see what I come up with.

**Comment by shiftkey** [comment]
> node-hid only supported up to Electron < 2.0 I think and still don't have prebuilds for the latest electron.

@adeperio check out the [latest release](https://github.com/node-hid/node-hid/releases/tag/v0.7.7) for `node-hid` as it looks like they've encountered the same problem as `keytar` and are now shipping prebuilds for Electron 4.0.4.

**Comment by adeperio** [comment]
Thanks @shiftkey yep latest release of node-hid is working, along with the latest keytar! Thanks!
