### ISSUE TITLE
Website is out of date

### ISSUE THREAD

**Issue by queeniema** [atom/node-keytar#167]
https://atom.github.io/node-keytar

Issues:
- `addPassword` => [`setPassword`](https://github.com/atom/node-keytar#setpasswordservice-account-password)
- `replacePassword` no longer exists
- does not include [`findCredentials`](https://github.com/atom/node-keytar#findcredentialsservice)

**Comment by shiftkey** [comment]
The website was generated six years ago next month 🍰 and sadly hasn't really gotten any love since.

The source for that is over on the [`gh-pages`](https://github.com/atom/node-keytar/tree/gh-pages) branch, and if someone cares enough to update this I'd happily help with reviewing changes.

**Comment by shiftkey** [comment]
Resolved in #200
