### ISSUE TITLE
Problem rebuilding for electron/macos

### ISSUE THREAD

**Issue by ncortines** [atom/node-keytar#172]
OS: macOS 10.14.4
NODE: 9.8.0
NPM: 5.6.0
KEYTAR: 4.4.1
ELECTRON: 2.0.0

I'm rebuilding keytar for electron using the following command:
```
cd build-temp && set npm_config_target=2.0.0 && set npm_config_arch=x64 && set npm_config_target_arch=ia32 && set npm_config_disturl=https://atom.io/download/electron && set npm_config_runtime=electron && set npm_config_build_from_source=true && npm rebuild keytar
```

At runtime ```require('keytar')``` produces this error:
```
Error: The module '/var/folders/cf/ppstqfl14rldvyxdvkvt8m9sjttv7_/T/.myapp.5PtI1W'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 59. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:186:18)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
```

I can't reproduce the error on Linux or Windows

**Comment by shiftkey** [comment]
`NODE_MODULE_VERSION 59` coincides with Node 9.x, and `NODE_MODULE_VERSION 57` coincides with Node 8.x (which is what Electron 2.x uses), so I guess the `npm rebuild` is ignoring your config and choosing the installed `node` to build against.

I'm not familiar with using `set` to manage environment variables (I prefer to declare them inline so they're only applied to the running script), but would something like this change the behaviour? The backticks are there to indicate the command continues on the next line...

```shellsession
npm_config_target=2.0.0 \
  npm_config_arch=x64 \
  npm_config_target_arch=ia32 \
  npm_config_disturl=https://atom.io/download/electron \
  npm_config_runtime=electron \
  npm_config_build_from_source=true \
  npm rebuild keytar
```

**Comment by ncortines** [comment]
Yes, it does change the behaviour. For some reason my version of the script works better in Windows. I'm closing this. Thanks for looking into this!
