### ISSUE TITLE
"Module did not self-register" error in electron

### ISSUE THREAD

**Issue by G0BL1N** [atom/node-keytar#184]
Because keytar does not implement win_delay_load_hook it's impossible to use it in Electron apps.
https://electronjs.org/docs/tutorial/using-native-node-modules#a-note-about-win_delay_load_hook

**Comment by G0BL1N** [comment]
Been able to fix it with electron-rebuild. I'm dumb, sorry.

**Comment by qqhann** [comment]
I had the same problem, and more specifically,
using electron-rebuild to rebuild keytar fixed it.
Thank you for the information.

**Comment by kevinlinv** [comment]
Welp... thanks for posting the solution here, this is helpful for beginner like me 😅

**Comment by mwroffo** [comment]
Excellent info.

**Comment by pjebs** [comment]
@G0BL1N Can you clarify your solution?

What is `electron-rebuild`?

**Comment by pjebs** [comment]
https://github.com/electron/electron-rebuild

Run `$(npm bin)/electron-rebuild`
