### ISSUE TITLE
'Set' is now deprecied with electron 5.x.x

### ISSUE THREAD

**Issue by popod** [atom/node-keytar#188]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Building with Electron 5.x.x, node 10.15.1 on macOS Mojave cause this warning:

```
CXX(target) Release/obj.target/keytar/src/async.o
../src/async.cc:193:12: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
      obj->Set(Nan::New("account").ToLocalChecked(), account);
           ^
/Users/xxx/.electron-gyp/.node-gyp/5.0.4/include/node/v8.h:3259:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/xxx/.electron-gyp/.node-gyp/5.0.4/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
../src/async.cc:194:12: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
      obj->Set(Nan::New("password").ToLocalChecked(), password);
           ^
/Users/xxx/.electron-gyp/.node-gyp/5.0.4/include/node/v8.h:3259:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/xxx/.electron-gyp/.node-gyp/5.0.4/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
```

**Comment by shiftkey** [comment]
This has been addressed in #186 but hasn't been published to NPM. I'll close this out one that's happened (some time this week).

**Comment by popod** [comment]
Nice, thanks !

**Comment by shiftkey** [comment]
This should be resolved with `v4.10.0` - let me know if you have any other suggestions or improvements to make...

**Comment by popod** [comment]
@shiftkey could you push this release to npm ? Thanks

**Comment by shiftkey** [comment]
@popod oops, I knew I forgot something. Fixed! https://www.npmjs.com/package/keytar/v/4.10.0
