### ISSUE TITLE
What to enter for "service"

### ISSUE THREAD

**Issue by henrygrover** [atom/node-keytar#19]
Hi, this may be a silly question, what is meant by "service"? I can't seem to figure it out, and can't find any good examples of how the service name required by keytar relates to gnome-keyring.

Thanks!

**Comment by kevinsawicki** [comment]
It relates to the Mac OS X keychain API which this was originally designed for. Other platforms were added later.

You can see the description here: https://developer.apple.com/library/mac/documentation/Security/Reference/keychainservices/index.html#//apple_ref/c/func/SecKeychainAddGenericPassword

It is basically just like an id or name to store the password for.

**Comment by kevinsawicki** [comment]
So really you can use whatever you want for it, it is just the value by which you can later ask for and delete the password.

**Comment by henrygrover** [comment]
Thanks for responding!

After importing Keytar, running keytar.addPassword("testService","accountName","password");
returns false

Any idea why that might be? I've done no other real setup, having thought that Keytar would just automatically deal with the keyring details. Was that an incorrect assumption?  Is it supposed to be as simple as npm installing keytar and then starting to use it, or am I missing some critical step/thinking about this wrong?

I'm on Fedora 21. gnome-keyring-daemon is running. I'm using node 0.10.35 and npm 1.4.28.  npm gave no errors on "npm install keytar"

Thanks for your help.

**Comment by kevinsawicki** [comment]
> Any idea why that might be? 

No sorry, I'd recommend cloning this repository and adding more debugging and then building it and testing it to get more details.

Sorry it doesn't have better error reporting

**Comment by henrygrover** [comment]
No worries! I will poke around some and let you know if I figure it out.
