### ISSUE TITLE
win32-x64 binaries missing from v4.10.0 release

### ISSUE THREAD

**Issue by dprothero** [atom/node-keytar#196]
None of the win32-x64 binaries were generated for the v4.10.0 release. They have been present in v4.9.0 and prior releases.

**Comment by shiftkey** [comment]
This should be fixed with `v4.11.0` that is being published right now.

**Comment by dprothero** [comment]
Wow, thanks for the quick fix on that!

Can I send you a Twilio t-shirt? Send me your size and mailing address: dprothero@twilio.com
