### ISSUE TITLE
can't install node-keytar on windows

### ISSUE THREAD

**Issue by Mohamed-Fakhry** [atom/node-keytar#216]
running `npm i` throws an error. I have node-keytar in my dependencies.
`C:\Users\Mohamd\.node-gyp\10.10.0\x64\node.lib : fatal error LNK1106: invalid file or disk full: cannot seek to 0x225F8 C [C:\Users\Mohamd\hodhod-electron\node_modules\keytar\build\keytar.vcxproj]`

**Comment by Mohamed-Fakhry** [comment]
```
                                                                                                                                                                        C:\Users\Mohamd\hodhod-electron>npm i                                                                                                                                                                                                                                                                                                           > keytar@5.0.0-beta.0 install C:\Users\Mohamd\hodhod-electron\node_modules\keytar                                                                                       > prebuild-install || node-gyp rebuild                                                                                                                                                                                                                                                                                                          prebuild-install WARN install No prebuilt binaries found (target=10.10.0 runtime=node arch=x64 libc= platform=win32)                                                                                                                                                                                                                            C:\Users\Mohamd\hodhod-electron\node_modules\keytar>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )   Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.                                                               async.cc                                                                                                                                                                main.cc                                                                                                                                                                 keytar_win.cc                                                                                                                                                           win_delay_load_hook.cc                                                                                                                                                C:\Users\Mohamd\.node-gyp\10.10.0\x64\node.lib : fatal error LNK1106: invalid file or disk full: cannot seek to 0x225F8                                                 C [C:\Users\Mohamd\hodhod-electron\node_modules\keytar\build\keytar.vcxproj]                                                                                            gyp ERR! build error                                                                                                                                                    gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1                             gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)                                          gyp ERR! stack     at ChildProcess.emit (events.js:182:13)                                                                                                              gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)                                                                            gyp ERR! System Windows_NT 10.0.17134                                                                                                                                   gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"               gyp ERR! cwd C:\Users\Mohamd\hodhod-electron\node_modules\keytar                                                                                                        gyp ERR! node -v v10.10.0                                                                                                                                               gyp ERR! node-gyp -v v3.8.0                                                                                                                                             gyp ERR! not ok  
```

**Comment by Mohamed-Fakhry** [comment]
`                                                                                                                    C:\Users\Mohamd\hodhod-electron>npm i                                                                                                                                                                                                           > keytar@5.0.0-beta.0 install C:\Users\Mohamd\hodhod-electron\node_modules\keytar                                       > prebuild-install || node-gyp rebuild                                                                                                                                                                                                          prebuild-install WARN install No prebuilt binaries found (target=10.10.0 runtime=node arch=x64 libc= platform=win32)                                                                                                                            C:\Users\Mohamd\hodhod-electron\node_modules\keytar>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )                           Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.               async.cc                                                                                                                main.cc                                                                                                                 keytar_win.cc                                                                                                           win_delay_load_hook.cc                                                                                                C:\Users\Mohamd\.node-gyp\10.10.0\x64\node.lib : fatal error LNK1106: invalid file or disk full: cannot seek to 0x225F8 C [C:\Users\Mohamd\hodhod-electron\node_modules\keytar\build\keytar.vcxproj]                                            gyp ERR! build error                                                                                                    gyp ERR! stack Error: `msbuild` failed with exit code: 1                                                                gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)                                                                                                                  gyp ERR! stack     at ChildProcess.emit (events.js:182:13)                                                              gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)                            gyp ERR! System Windows_NT 10.0.17134                                                                                   gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"                                                                                       gyp ERR! cwd C:\Users\Mohamd\hodhod-electron\node_modules\keytar                                                        gyp ERR! node -v v10.10.0                                                                                               gyp ERR! node-gyp -v v3.8.0                                                                                             gyp ERR! not ok       `

**Comment by shiftkey** [comment]
> fatal error LNK1106: invalid file or disk full: cannot seek to 0x225F8

Could the disk be full? 🤔

**Comment by Mohamed-Fakhry** [comment]
there is 50 GBs of free space...
I changed keytar version from 5.0.0-beta to 4.13.0 and that fixed the problem!

**Comment by shiftkey** [comment]
@Mohamed-Fakhry aha, so you're on Windows and Appveyor didn't publish the prebuild release, so it fell back to the default behaviour.

I guess that error is related to something else other than disk space, but for now I'm going to mention this in https://github.com/atom/node-keytar/issues/212 and close this out - we plan to ship prebuild binaries for `5.0.0`, so using the last stable release is fine for now.
