### ISSUE TITLE
Electron 7 support

### ISSUE THREAD

**Issue by magne4000** [atom/node-keytar#231]
### Description
Installing the package with Electron 7 currently throws on `getPassword`.
It doesn't even throw an error, it throws the number `32766`.

I try to force rebuild with `electron-rebuild -f -o keytar` but it doesn't seem to do anything.
Custom `.npmrc` doesn't do the trick either.

**Comment by magne4000** [comment]
Found a way to force rebuild: `yarn run node-gyp rebuild --target=7.0.0 --arch=x64 --dist-url=https://electronjs.org/headers --runtime=electron -C node_modules/keytar`

**Comment by shiftkey** [comment]
@magne4000 I'd take a PR to convert these beta tags for Electron 7 into the stable version (probably also needs to bump `node-abi`):

https://github.com/atom/node-keytar/blob/90e995cdf9812a370a00009b3240bb518816e5a8/package.json#L39-L40

**Comment by magne4000** [comment]
@shiftkey here you go! https://github.com/atom/node-keytar/pull/233

**Comment by shiftkey** [comment]
@magne4000 I've published this up to NPM with [`5.0.0-beta4`](https://github.com/atom/node-keytar/releases/tag/v5.0.0-beta.4) and I'll promote this to `5.0.0` later in the week. Details on the breaking changes are listed here https://github.com/atom/node-keytar/releases/tag/v5.0.0-beta.0
