### ISSUE TITLE
5.0.0-beta.4 version mistakenly tagged as latest

### ISSUE THREAD

**Issue by bmish** [atom/node-keytar#234]
Presumably since `5.0.0-beta.4` is a beta version, it should not be tagged as `latest`.

This beta version shows up as `latest` when checking `npm info keytar` or visiting the npm registry (https://www.npmjs.com/package/keytar).

By tagging this beta version as `latest`, it gets automatically installed by `npm install keytar` and similar commands, and in particular some automated tooling which can lead to broken builds.

The fix would be to remove the `latest` tag from this beta version and optionally add it back to the last stable version `4.13.0`. Using `yarn publish --tag beta` can help avoid this issue in the future.

CC: @shiftkey

**Comment by shiftkey** [comment]
@bmish thanks for the heads up. This has now been updated on NPM:

<img width="783" src="https://user-images.githubusercontent.com/359239/67855159-ab077b00-faf0-11e9-9334-1636d0e157aa.png">

I plan to promote `5.0.0-beta.4` to `5.0.0` later this week, so please let me know if you spot anything unexpected.
