### ISSUE TITLE
Require fail in Electron 0.28.3 on Mac OS 10.10.3

### ISSUE THREAD

**Issue by ffaubry** [atom/node-keytar#26]
I installed keytar in my Electron app: npm i keytar --save
I got the following output:
```
npm WARN package.json operations-dashboard@0.1.0 No repository field.
npm WARN package.json operations-dashboard@0.1.0 No README data
\
> keytar@2.1.0 install /Users/fred/Documents/WebProjects/radon/node_modules/keytar
> node-gyp rebuild

  CXX(target) Release/obj.target/keytar/src/main.o
  CXX(target) Release/obj.target/keytar/src/keytar_mac.o
  SOLINK_MODULE(target) Release/keytar.node
keytar@2.1.0 node_modules/keytar
└── nan@1.6.1
```

In my main.js added ```var keytar = require("keytar");```

I'm getting:
```App threw an error when running [Error: Module version mismatch. Expected 44, got 14.]```

If I remove the require("keytar") the app is working again.

**Comment by maxbrunsfeld** [comment]
The `keytar` module needs to be compiled against Electron's version of V8. See the docs on using native node modules: http://electron.atom.io/docs/v0.28.0/tutorial/using-native-node-modules/.

Let me know if you have more questions.

**Comment by ffaubry** [comment]
@maxbrunsfeld Thanks, that was my issue.
