### ISSUE TITLE
Electron 9.0.0-beta.16 crashes when importing node-keytar

### ISSUE THREAD

**Issue by sentialx** [atom/node-keytar#261]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description
Electron 9.0.0-beta.16 crashes with exit code `3221225477` when just importing `node-keytar` rebuilt using electron-builder.

### Steps to Reproduce

Just type the following in an Electron app.
```ts
require('keytar');
```

**Reproduces how often:**

Always

### Versions

* Windows 10
* node-keytar 5.4.0
* Electron 9.0.0-beta.16

**Comment by sentialx** [comment]
Any update?

**Comment by shiftkey** [comment]
@sentialx not really, haven't had time to dust off a Windows machine. 

Looking at the exit code, it seems like it's related to memory access, based on [this comment](https://github.com/electron/electron/issues/3570#issuecomment-159330269):

> Here's how to interpret this number - open WinDbg (from the Windows SDK) on any file, then type this into the command window:
> 
> ```
> notepad+0x18ef0:
> 00000001`40018ef0 4883ec28        sub     rsp,28h
> 
> 0:000> .formats 0n3221225477
> Evaluate expression:
>   Hex:     00000000`c0000005    <-----
>   Decimal: 3221225477
>   Octal:   0000000000030000000005
>   Binary:  00000000 00000000 00000000 00000000 11000000 00000000 00000000 00000101
>   Chars:   ........
>   Time:    ***** Invalid
>   Float:   low -2 high 0
>   Double:  1.5915e-314
> 
> 0:000> !error c0000005
> Error code: (NTSTATUS) 0xc0000005 (3221225477) - The instruction at 0x%p referenced memory at 0x%p. The memory could not be %s.
> ```
> 
> Looks like a crash in native code

A runnable example that illustrates the problem here would be helpful - for example, it's not clear to me whether you're requiring `require('keytar');` in the main process or the renderer. This would also help confirm it's not related to something else.

**Comment by shiftkey** [comment]
> rebuilt using electron-builder

I'd also like to confirm this isn't something that `electron-builder` is introducing - you might have to wait for them to support Electron 9...

**Comment by sentialx** [comment]
I'm calling require in the main process. I believe it's not electron-builder issue since my other native node addons work perfectly.

**Comment by sentialx** [comment]
Last version of Electron in which I saw keytar was working fine was 9.0.0-beta.6.

**Comment by shiftkey** [comment]
To get a runnable example I made these changes to `electron-quick-start`, importing the module as late as possible:

```
$ git rev-parse HEAD
d2db0d4cc1f7ebcf6c562eeb5d5e3a8eabd0432e

$ git diff -- package.json main.js
diff --git a/main.js b/main.js
index c4d7e19..bce4a7e 100644
--- a/main.js
+++ b/main.js
@@ -3,6 +3,10 @@ const {app, BrowserWindow} = require('electron')
 const path = require('path')

 function createWindow () {
+  console.log(`Loading keytar...`);
+  const keytar = require('keytar');
+  console.log(`Loaded keytar, displaying window...`);
+
   // Create the browser window.
   const mainWindow = new BrowserWindow({
     width: 800,
diff --git a/package.json b/package.json
index f747f34..a4c5bf5 100644
--- a/package.json
+++ b/package.json
@@ -16,7 +16,10 @@
   ],
   "author": "GitHub",
   "license": "CC0-1.0",
+  "dependencies": {
+    "keytar": "^5.5.0"
+  },
   "devDependencies": {
-    "electron": "^8.2.3"
+    "electron": "9.0.0-beta.19"
   }
 }
```

I then `npm i && npm start` to launch the app and it does get stuck, but in a different way:

```
$ npm i && npm start

> keytar@5.5.0 install C:\Users\shiftkey\src\electron-quick-start\node_modules\keytar
> prebuild-install || node-gyp rebuild


> core-js@3.6.5 postinstall C:\Users\shiftkey\src\electron-quick-start\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> electron@9.0.0-beta.19 postinstall C:\Users\shiftkey\src\electron-quick-start\node_modules\electron
> node install.js

added 134 packages from 132 contributors and audited 202 packages in 6.038s
found 0 vulnerabilities


> electron-quick-start@1.0.0 start C:\Users\shiftkey\src\electron-quick-start
> electron .


Loading keytar...
(node:7060) UnhandledPromiseRejectionWarning: Error: Module did not self-register: '\\?\C:\Users\shiftkey\src\electron-quick-start\node_modules\keytar\build\Release\keytar.node'.
    at process.func (electron/js2c/asar.js:140:31)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
    at Object.func (electron/js2c/asar.js:140:31)
    at Object.func [as .node] (electron/js2c/asar.js:140:31)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Module._load (electron/js2c/asar.js:738:28)
    at Function.Module._load (electron/js2c/asar.js:738:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
(node:7060) UnhandledPromiseRejectionWarning: Error: Module did not self-register: '\\?\C:\Users\shiftkey\src\electron-quick-start\node_modules\keytar\build\Release\keytar.node'.
    at process.func (electron/js2c/asar.js:140:31)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
    at Object.func (electron/js2c/asar.js:140:31)
    at Object.func [as .node] (electron/js2c/asar.js:140:31)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Module._load (electron/js2c/asar.js:738:28)
    at Function.Module._load (electron/js2c/asar.js:738:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
(node:7060) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7060) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7060) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:7060) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

This is because `npm` is going to use the installed version of `node` to obtain any prebuilt binaries, so I added an `.npmrc` file to ensure we're using the right version when `prebuild-install` runs:

```
$ git add .npmrc

$ cat .npmrc
runtime = electron
disturl = https://atom.io/download/electron
target = 9.0.0-beta.19
arch = x64

$ git clean -xdf
Removing node_modules/

$ npm i

> keytar@5.5.0 install C:\Users\shiftkey\src\electron-quick-start\node_modules\keytar
> prebuild-install || node-gyp rebuild


> core-js@3.6.5 postinstall C:\Users\shiftkey\src\electron-quick-start\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> electron@9.0.0-beta.19 postinstall C:\Users\shiftkey\src\electron-quick-start\node_modules\electron
> node install.js

added 134 packages from 132 contributors and audited 202 packages in 14.837s
found 0 vulnerabilities
```

Cool, still looks to be using the prebuild version. Let's run it again:

```
$ npm start

> electron-quick-start@1.0.0 start C:\Users\shiftkey\src\electron-quick-start
> electron .


Loading keytar...
npm ERR! code ELIFECYCLE
npm ERR! errno 3221225477
npm ERR! electron-quick-start@1.0.0 start: `electron .`
npm ERR! Exit status 3221225477
npm ERR!
npm ERR! Failed at the electron-quick-start@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\shiftkey\AppData\Roaming\npm-cache\_logs\2020-04-26T13_37_47_447Z-debug.log
/c/Program Files/nodejs/npm: line 37:   684 Segmentation fault      "$NODE_EXE" "$NPM_CLI_JS" "$@"
```

Running it outside of `npm` might help with yielding how the native module is failing, but for now that helps me get up to speed.

**Comment by shiftkey** [comment]
> Last version of Electron in which I saw keytar was working fine was 9.0.0-beta.6.

I've been able to load the module successfully in `9.0.0-beta9`, and the earliest crashing version I can find is `9.0.0-beta10`.

<img width="1094" src="https://user-images.githubusercontent.com/359239/80309544-1e422f00-87ac-11ea-8168-d35b15f0ff91.png">

That points to the problem being introduced somewhere in here: https://github.com/electron/electron/compare/v9.0.0-beta.9...v9.0.0-beta.10

Aside from the Chromium bump I can't spot any obvious clues that would explain the segfault behaviour. Might need to build Electron from source to get more context about the problem.

**Comment by shiftkey** [comment]
I rebuilt keytar against `v9.0.0-beta.10` and was able to launch the Electron app as expected:

<img width="1071"  src="https://user-images.githubusercontent.com/359239/80310143-8a726200-87af-11ea-8e7d-27b9af62d996.png">

Same thing with `v9.0.0-beta.16`:

<img width="1083" src="https://user-images.githubusercontent.com/359239/80310174-c6a5c280-87af-11ea-8658-69f831a8886e.png">

Thus, I believe the Chromium bump was the root cause of this change, and given we were previously building against `v9.0.0-beta.2` I think #263 is the fix here.

**Comment by sentialx** [comment]
Thanks for your time in investigating the problem!
