### ISSUE TITLE
build problems with electron 4.1.4

### ISSUE THREAD

**Issue by Wonder233** [atom/node-keytar#273]
Seeing this when running `electron-builder install-app-deps`
```
build native dependency from sources  name=keytar
                                          version=6.0.0
                                          platform=darwin
                                          arch=x64
                                          reason=prebuild-install failed with error (run with env DEBUG=electron-builder to get more information)
                                          error=prebuild-install info begin Prebuild-install version 5.3.3
prebuild-install WARN install prebuilt binaries enforced with --force!
prebuild-install WARN install prebuilt binaries may be out of date!
prebuild-install info looking for cached prebuild @ /Users/wonder/.npm/_prebuilds/d11da4-keytar-v6.0.0-electron-v69-darwin-x64.tar.gz
prebuild-install http request GET https://github.com/atom/node-keytar/releases/download/v6.0.0/keytar-v6.0.0-electron-v69-darwin-x64.tar.gz
prebuild-install http 404 https://github.com/atom/node-keytar/releases/download/v6.0.0/keytar-v6.0.0-electron-v69-darwin-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=4.1.4 runtime=electron arch=x64 libc= platform=darwin)
```

and when I open "https://github.com/atom/node-keytar/releases/download/v6.0.0/keytar-v6.0.0-electron-v69-darwin-x64.tar.gz", it exactly not found.
How can I solve this problem?

**Comment by shiftkey** [comment]
@Wonder233 Electron v4 support was removed in keytar [v5.0.0](https://github.com/atom/node-keytar/releases/tag/v5.0.0) as the Electron project was no long supporting that release with bugfixes or security updates.

I recommend looking into upgrading to a more recent version of Electron, as we try to follow their support lifecycle. In the meantime, pinning to the latest `v4.x` version of keytar (as mentioned in the release notes) should ensure you can build the project.
