### ISSUE TITLE
drop Electron v5 and v6 support for the next major release

### ISSUE THREAD

**Issue by shiftkey** [atom/node-keytar#276]
This aligns us with the current supported versions of Electron: https://www.electronjs.org/docs/tutorial/support

This simply requires dropping the two versions from these lines in `package.json`:

https://github.com/atom/node-keytar/blob/60aa824f4ce4bb99ef3c0c71c86982c0a45c0f1b/package.json#L39-L40

**Comment by kamilbeker** [comment]
On it.

**Comment by shiftkey** [comment]
This happened in #311
