### ISSUE TITLE
drop Node 8 and 9 support for next major release

### ISSUE THREAD

**Issue by shiftkey** [atom/node-keytar#277]
This aligns us with the current NodeJS LTS schedule: https://github.com/nodejs/release

https://github.com/atom/node-keytar/blob/60aa824f4ce4bb99ef3c0c71c86982c0a45c0f1b/package.json#L37-L38

This change is a bit trickier as it'll mean we no longer have any 32-bit prebuild versions in use, which may require cleaning up some other parts of the infrastructure, so I won't mark this as `help-wanted`.

Windows appears to be the only OS that they ship official 32-bit Node releases for currently, and given we haven't shipped a new 32-bit prebuild update in over 2 years (1a98c5a57771d8c61bee78b6b286850fbf2cfce2) I suspect no-one is using it.

**Comment by BananaAcid** [comment]
Will this effect any current electron releases?

**Comment by shiftkey** [comment]
@BananaAcid those are handled differently, and are tracked here https://www.electronjs.org/docs/tutorial/support#supported-versions
