### ISSUE TITLE
Install fails under io.js 3.0.0

### ISSUE THREAD

**Issue by limulus** [atom/node-keytar#28]
It appears that, in order to be compatible with io.js v3, it is necessary to update to nan v2.

I cloned the repo, updated the dependency, but it appears that the breaking changes that come along with nan v2 affect keytar, so that failed.

I'm not sure why the nan dependency is a static link to `atom.io` and not a semver range for downloading from an npm repository. Switching to a more standard `^2.0.0` range would probably be helpful to get more timely support for new versions of Node. (Though it obviously won't help in the case of a breaking change like this one.)

Thanks for this module! It’s a really slick cross-platform abstraction!

**Comment by kevinsawicki** [comment]
> I'm not sure why the nan dependency is a static link to atom.io and not a semver range for downloading from an npm repository. 

This is because this module was used by Atom and a custom nan version was needed during a Chromium/io.js upgrade Atom was going through.

**Comment by ariporad** [comment]
@kevinsawicki: Hi, I didn't really understand your comment, but do you know if/when this module will be compatable with iojs 3.0.0

**Comment by kevinsawicki** [comment]
> but do you know if/when this module will be compatable with iojs 3.0.0?

I don't know when. I haven't looked into what nan changes are required to get it working again on iojs 3.0.0.

**Comment by ariporad** [comment]
Ok, Thanks.



Ari

**Comment by ffaubry** [comment]
+1 for a fix

**Comment by vijayendranj** [comment]
+1 for a fix

**Comment by ToMaHaWk** [comment]
+1 Need this

**Comment by ChALkeR** [comment]
Adding to the list: https://github.com/nodejs/node/issues/2798.

**Comment by limulus** [comment]
3.0.0 is working well for me on Node 4.0.0 (and Node 0.12.7 for that matter). Thank you all! :100:

**Comment by ffaubry** [comment]
Thanks guys. Just pulled Electron 0.32.1 and keytar. And the magic is back.

**Comment by vijayendranj** [comment]
Thx
