### ISSUE TITLE
Could not detect abi for version 9.1.0 and runtime electron

### ISSUE THREAD

**Issue by keithslater** [atom/node-keytar#288]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Keytar doesn't build on Electron 9.1.0

### Steps to Reproduce

1. Install electron 9.1.0 and keytar

**Expected behavior:**

Keytar to build successfully

**Actual behavior:**

`Could not detect abi for version 9.1.0 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron`

**Reproduces how often:**

100%

### Versions

electron: 9.1.0
electron-builder: 22.7.0
keytar: 6.0.1
node: 12.14.1

**Comment by shiftkey** [comment]
@keithslater which version(s) of `node-abi` do you have in your package? 

```
npm ls node-abi
```


It might be that a local version is older than the one we depend on in `v6.0.0` when we added the prebuild support for Electron 9.

**Comment by keithslater** [comment]
node-abi@2.9.0

Is there a way to force it to use the one you recommend (2.17.0)? I tried installing it manually but got the same error. When I do `npm ls node-abi`, it then says:

```├─┬ keytar@6.0.1
│ └─┬ prebuild-install@5.3.4
│   └── node-abi@2.9.0
└── node-abi@2.17.0

**Comment by shiftkey** [comment]
I'm very rusty on updating transient dependencies using `npm` (`yarn` 1.x [does support this](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/)), so I'm not sure offhand. 

I installed the latest version into `electron-quick-start` and it's choosing the latest version of `node-abi`, which is what we'd expect here:

```
$ npm ls node-abi
electron-quick-start@1.0.0 /Users/shiftkey/src/electron-quick-start
└─┬ keytar@6.0.1
  └─┬ prebuild-install@5.3.4
    └── node-abi@2.18.0
```

**Comment by keithslater** [comment]
I'm actually using yarn. I was able to add this to my package.json and it resolved the issue. Thanks

```
  "resolutions": {
    "lgeiger/node-abi": "^2.18.0"
  }
