### ISSUE TITLE
quasar and keytar

### ISSUE THREAD

**Issue by Amosss** [atom/node-keytar#291]
Hi
I develop using Quasar and I'm trying to figure out how to integrate keytar. In the code I tried both `const keytar = require("keytar");` and `import {keytar} from "keytar"`. Both resulted with the following error:
> Module parse failed: Unexpected character '�' (1:2)
> You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> (Source code omitted for this binary file)

I searched for it and got here: https://stackoverflow.com/questions/59205156/unable-to-use-keytar-in-main-js-of-electron-project but I didn't understand how/where should I integrate it into quasar.conf.js also I'm not sure which of the 2 suggested solutions is correct. Maybe both of them?

Moreover, originally I develop for the web and only when building, I (also) build in electron mode so do I need to distinguish the "import" to happen only in electron mode? I'm a bit confused.  Any advice will be appreciated, thanks.

**Comment by Amosss** [comment]
I also saw this https://github.com/atom/node-keytar/issues/59#issuecomment-279406165 but I didn't understand where should I put it.

**Comment by shiftkey** [comment]
I'm not familiar with Quasar at all so I'm not 100% sure of these answers, but here goes:

> I didn't understand how/where should I integrate it into quasar.conf.js also I'm not sure which of the 2 suggested solutions is correct. Maybe both of them?

The first solution - integrating a loader for native node modules into webpack - is what you should be aiming for here.

> I (also) build in electron mode so do I need to distinguish the "import" to happen only in electron mode?

I have no idea. Generally whether you can `import` or need to `require` depends on what version of JavaScript/ECMAScript you are trying to target. I'd focus on using `require` until you know everything else works.

**Comment by Amosss** [comment]
Just to be sure, you you mean I should aim for this one?
```
// vue.config.js
configureWebpack: {
    devtool: 'source-map',
    module: {
      rules: [
        { test: /\.node$/, loader: 'node-loader' }
      ]
    }
  }
```

**Comment by shiftkey** [comment]
I'm not sure that `vue.config.js` is the right config to change for your Quasar project, but that's on the right track

**Comment by Amosss** [comment]
It's not, quasar has its own conf.js, I referred to the solution itself :) Thanks

**Comment by Amosss** [comment]
I (think) I found the place where to put the above code and now it is compiled but when the page opens up, it's empty. The console says: 

> Cannot open C:\Users\user\Downloads\portable\vscode\Projects\project\node_modules\keytar\build\Release\keytar.node: TypeError: Cannot read property 'dlopen' of undefined
>     at Object.eval (keytar.node?3002:1)

and the line itself is
`try {global.process.dlopen(module, "C:\\Users\\user\\Downloads\\portable\\vscode\\Projects\\project\\node_modules\\keytar\\build\\Release\\keytar.node"); } catch(e) {throw new Error('Cannot open ' + "C:\\Users\\user\\Downloads\\portable\\vscode\\Projects\\project\\node_modules\\keytar\\build\\Release\\keytar.node" + ': ' + e);}`
Obviously `global.process` is undefined.

I wonder if it’s because keytar should only be loaded in electron mode? 
If so, how can I set it to load only in electron mode? 
If not, what am I doing wrong?
Thanks

**Comment by shiftkey** [comment]
@Amosss this is the first time i've heard of quasar so sadly I cannot really help you much more at this stage.

I'm going to close this out as it's external to the project, but please update us if you're able to figure out how to get this working...

**Comment by Amosss** [comment]
Hi, 

The last issue I posted seems not to be related to quasar (I passed quasar fault). It looks like a keytar issue that might be happening because I did something wrong.

I posted here what is the error and from where it comes from, will more information help here? If so, what info is required?
If it's not related to keytar, where else can I look into it?
Thanks

**Comment by shiftkey** [comment]
>  More specifically, what is `global.process` and who owns it?

This is part of `node-loader`:

https://github.com/webpack-contrib/node-loader/blob/8906f3b6eb0346bf2de5bcdf9c7f0b82c334f253/src/index.js#L30-L42

**Comment by Amosss** [comment]
Thank you very much! I'll continue there
