### ISSUE TITLE
DeprecationWarning: crypto.createDecipher is deprecated.

### ISSUE THREAD

**Issue by vicky16898** [atom/node-keytar#308]
Getting a deprecation warning whenever I try to get the password using service and account name.

**Comment by shiftkey** [comment]
@vicky16898 it's not clear to me how this relates to keytar.

Are you able to provide an example and more details about your setup (which OS, which version of Node, etc).

**Comment by shiftkey** [comment]
Closing this out due to lack of information.

Example code or script that shows how `keytar` is involved with the related error is what's needed investigate further.
