### ISSUE TITLE
Can only install with -g

### ISSUE THREAD

**Issue by davidhealey** [atom/node-keytar#316]
I get this when trying to install keytar, however if I use -g it works without complaining...

`npm install keytar

> keytar@7.0.0 install /media/dave/Work 1/Projects/tools/hise-exporter/node_modules/keytar
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=14.12.0 runtime=node arch=x64 libc= platform=linux)
make: Entering directory '/media/dave/Work 1/Projects/tools/hise-exporter/node_modules/keytar/build'
  CXX(target) Release/obj.target/keytar/src/async.o
g++: error: 1/Projects/tools/hise-exporter/node_modules/node-addon-api: No such file or directory
make: *** [keytar.target.mk:117: Release/obj.target/keytar/src/async.o] Error 1
make: Leaving directory '/media/dave/Work 1/Projects/tools/hise-exporter/node_modules/keytar/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/dave/.nvm/versions/node/v14.12.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 4.19.0-12-amd64
gyp ERR! command "/home/dave/.nvm/versions/node/v14.12.0/bin/node" "/home/dave/.nvm/versions/node/v14.12.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /media/dave/Work 1/Projects/tools/hise-exporter/node_modules/keytar
gyp ERR! node -v v14.12.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN hise-exporter@0.0.1 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keytar@7.0.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keytar@7.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dave/.npm/_logs/2020-10-28T01_59_35_412Z-debug.log
`

**Comment by shiftkey** [comment]
> make: Entering directory '/media/dave/Work 1/Projects/tools/hise-exporter/node_modules/keytar/build'

Looks like the presence of a space in the path is the same as #315, but for a different OS. I'm going to add a note to that issue and close this out, but in the meantime the recommended workaround from #315 is to avoid paths with spaces in them (or use a version of Node/Electron that handles prebuild).
