### ISSUE TITLE
migrate to GitHub Actions for building and publishing releases

### ISSUE THREAD

**Issue by shiftkey** [atom/node-keytar#320]
Looks like `travis-ci.org` is being closed down at the end of the year, and projects are being [migrated](https://docs.travis-ci.com/user/migrate/open-source-repository-migration) to `travis-ci.com`.

While a [free tier remains on travis-ci.com](https://travis-ci.com/plans) it seems this may quickly consume the free credits when having to build each on macOS, Windows and Linux for a run.

Let's take this opportunity to get a simple Actions workflow setup:

 - [x] on pull request and push to default branch, build and test on each platform - #323 
 - [ ] on tag, build, package and publish the binaries to GitHub
 - [ ] stretch goal: on tag, publish to NPM

Open questions:

 - ~~will the Electron ARM64 work in #319 continue to work fine on Actions?~~ not currently

**Comment by dennisameling** [comment]
Regarding publishing to NPM on a new tag: here's a GH Actions workflow for a different repo where I did that (your scenario might be a bit more complex I guess): https://github.com/dennisameling/muuri-angular/blob/master/.github/workflows/npm-publish.yml

On tag, build & publish to GitHub: here's a repo where I did that for an open source marketing automation tool: https://github.com/mautic/mautic/blob/staging/.github/workflows/release.yml#L53-L86

Not sure if this helps at all, just wanted to share this for inspiration! Let me know if I can be of any help in this process 🚀

**Comment by vladimiry** [comment]
Is there specific reason for having ubuntu-16.04 in the config file but not 18.04 or 20.04? If this is about setting up gnome-keyring I think I could help here since was recently handling the task for https://github.com/vladimiry/ElectronMail.

**Comment by shiftkey** [comment]
@vladimiry the Travis build was running 16.04 so I think that's why I stuck with that version, but I think this was also related to `python-gnomekeyring` - there's more context in this discussion about upgrading but I left it as there were more pressing things to tackle at the time https://askubuntu.com/questions/1080896/what-replaced-pythons-gnomekeyring-module-in-ubuntu-18-04-bionic

**Comment by vladimiry** [comment]
Ok, going to make a PR soon.

**Comment by vladimiry** [comment]
The PR is #342.
