### ISSUE TITLE
Consider only offering prebuilds for N-API v3

### ISSUE THREAD

**Issue by dennisameling** [atom/node-keytar#330]
## Summary

Since Node 8.11.2, N-API v3 [has been supported](https://nodejs.org/api/n-api.html#n_api_n_api_version_matrix). `node-keytar` is already built on N-API, but is still providing many prebuilds for Electron and NodeJS. Downside of this is that with every new major version release of either NodeJS or Electron, [those prebuild targets have to be added](https://github.com/atom/node-keytar/pull/329).

Major libraries like `sharp` [are now switching to N-API prebuilds only](https://github.com/lovell/sharp/releases). E.g. if you compare Sharp [0.25.4](https://github.com/lovell/sharp/releases/tag/v0.25.4) to [0.26.3](https://github.com/lovell/sharp/releases/tag/v0.26.3), you'll see that in the newer version, only 6 prebuilds were needed, compared to 72 in the older one.

Building `node-keytar` for N-API is already possible today by running `prebuild -t 3 -r napi`. 

Are you OK with switching to N-API prebuilds only, or are there reasons not to do that? I'm happy to provide a PR for it.

## Motivation

Significantly reduces the amount of prebuilds that need to be generated for `node-keytar`. 

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by shiftkey** [comment]
> Are you OK with switching to N-API prebuilds only, or are there reasons not to do that? I'm happy to provide a PR for it.

I'm mostly holding off on the switch because N-API support is a recent addition - https://github.com/atom/node-keytar/pull/268

As we stop supporting older versions of Node I'm 👍 to seeing when we can cutover to N-API only. Happy to review a PR and figure out when we want to make that happen.
