### ISSUE TITLE
Linux arm64 prebuilt binary is not detected

### ISSUE THREAD

**Issue by quanglam2807** [atom/node-keytar#335]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

`linux-arm64` prebuilt binary is available but somehow, it doesn't work

### Steps to Reproduce

1. `yarn add keytar`
```bash
error /home/quanglam2807/Documents/GitHub/webcatalog-engine/node_modules/keytar: Command failed.
Exit code: 1
Command: prebuild-install || npm run build
Arguments: 
Directory: /home/quanglam2807/Documents/GitHub/webcatalog-engine/node_modules/keytar
Output:
prebuild-install WARN install No prebuilt binaries found (target=12.18.2 runtime=node arch=arm64 libc= platform=linux)
npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1606102286826-0.4631994582883505/node but npm is using /usr/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> keytar@7.2.0 build /home/quanglam2807/Documents/GitHub/webcatalog-engine/node_modules/keytar
> node-gyp rebuild

Package libsecret-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libsecret-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libsecret-1' found
gyp: Call to 'pkg-config --cflags libsecret-1' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/nodejs/node-gyp/lib/configure.js:354:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.8.0-1007-raspi
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/quanglam2807/Documents/GitHub/webcatalog-engine/node_modules/keytar
gyp ERR! node -v v12.18.2
gyp ERR! node-gyp -v v7.0.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keytar@7.2.0 build: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keytar@7.2.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.


```

**Expected behavior:** prebuilt binary is downloaded

**Actual behavior:** prebuilt binary is not found. `keytar` attempts to build binary from source.

**Reproduces how often:**

### Versions
electron@10.1.5
keytar@7.2.0

**Comment by quanglam2807** [comment]
So in this case, `yarn` attempts to install the `arm64` binary for `node` runtime which at the moment, `keytar` doesn't provide prebuilt binary (it only provides `arm64` binary` for `electron` runtime).

**Comment by shiftkey** [comment]
> So in this case, `yarn` attempts to install the `arm64` binary for `node` runtime which at the moment, `keytar` doesn't provide prebuilt binary (it only provides `arm64` binary`for`electron` runtime).

You need to tell `npm` via an `.npmrc` file at the root that you want a different arch and version, otherwise it reverts to the currently running `node` version.

Here's the version for GitHub Desktop, for example:

https://github.com/desktop/desktop/blob/development/app/.npmrc

```
runtime = electron
disturl = https://atom.io/download/electron
target = 9.3.1
arch = x64
```

Place it in the same directory as your `package.json` and try again.

**Comment by quanglam2807** [comment]
Thank you, @shiftkey. I'll close this thread. I'll test more carefully but I'm certain that this is unrelated to https://github.com/atom/node-keytar/issues/318. `electron-builder` downloads native components using the correct runtime configuration regardless of `.npmrc`.
