### ISSUE TITLE
Electron v12 builds are missing

### ISSUE THREAD

**Issue by sirtimid** [atom/node-keytar#369]
It seems the electron v12 prebuilds are missing:

keytar-v7.4.0-electron-v87-darwin-x64.tar.gz
keytar-v7.4.0-electron-v87-linux-x64.tar.gz
keytar-v7.4.0-electron-v87-windows-x64.tar.gz

Can you generate them? Thanks

**Comment by danhowitt** [comment]
Looks like a new release will kick it off.

**Comment by h-yahia** [comment]
I have the same issue.

**Comment by jmeinke** [comment]
We'd be interested in 32bit prebuilt binaries as well :)

**Comment by azeier** [comment]
@shiftkey Any news on getting a new release?

**Comment by nicograef** [comment]
This would help me too! :)

**Comment by shiftkey** [comment]
Done: https://github.com/atom/node-keytar/releases/tag/v7.5.0

**Comment by nicograef** [comment]
Thank you @shiftkey ! :)

**Comment by sirtimid** [comment]
Thank you!!!
