### ISSUE TITLE
404 on prebuild-install download for electron

### ISSUE THREAD

**Issue by SteveLewisZA** [atom/node-keytar#392]
Hi there,

I see an error coming up when packaging an electron app, appears to be trying to download a package for electron which does not exist online, here is link:

https://github.com/atom/node-keytar/releases/download/v7.7.0/keytar-v7.7.0-electron-v89-win32-ia32.tar.gz

I see this does not exist in releases

Thanks,
Steve

**Comment by sergiou87** [comment]
Hi @SteveLewisZA! 👋 

This is the same problem described in #380. I'm sorry but that seems to be a known issue in electron-builder. Please take a look at https://github.com/atom/node-keytar/issues/380#issuecomment-830623319 for more info.

I hope that helps!
