### ISSUE TITLE
npm install keytar error on windows 10

### ISSUE THREAD

**Issue by wangxiexe** [atom/node-keytar#45]
C:\Users\wangxi\git\micloud-pc\app\node_modules\keytar>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )

  main.cc
  keytar_win.cc
  win_delay_load_hook.c
C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.c(34): error C2373: '__pfnDliNot
ifyHook2': redefinition; different type modifiers [C:\Users\wangxi\git\micloud-pc\app\node_modules\keytar\build\keytar.
vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\delayimp.h(134): note: see declaration of '__pfnDliNot
  ifyHook2'
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)

**Comment by wangxiexe** [comment]
the cause is here

https://github.com/nodejs/node-gyp/issues/972

**Comment by cloudresourcemanagergoogleapis** [comment]
#85

**Comment by Cath2022** [comment]
Leave comment
