### ISSUE TITLE
Method to retrieve a list of services from the password manager.

### ISSUE THREAD

**Issue by dcbartlett** [atom/node-keytar#56]
I think adding a method that would give you a list of the stored services/accounts would be useful.  My current project needs this functionality.

I'm not good at c++ code, however, i know there are a lot of smart people in the community and i believe this would benefit the community as a whole.  If someone would be so kind as to create the methods for the OS's and then provide that to the javascript interface, i would be extremely grateful.

**Comment by klorenz** [comment]
+1
.e.g. findCredentials(service), find all account/password pairs for given service
