### ISSUE TITLE
Unable to install keytar on windows 10 node 6.9, npm 4.3

### ISSUE THREAD

**Issue by abondoa** [atom/node-keytar#61]
I am trying to install keytar as part of an electron app, by running 

`npm install keytar`

I am getting the following error:

```
> keytar@3.0.2 install C:\Users\AlexBondo\code-playground\GameQuestLauncher\src\node_modules\keytar
> node-gyp rebuild


C:\Users\AlexBondo\code-playground\GameQuestLauncher\src\node_modules\keytar>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  els
e (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Users\AlexBondo\AppData\Local\Programs\Python\Python35-32\python.exe", you can set the PYTHON env variable.
gyp ERR! stack     at Object.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:454:19)
gyp ERR! stack     at Object.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:480:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\AlexBondo\code-playground\GameQuestLauncher\src\node_modules\keytar
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "keytar"
npm ERR! node v6.9.5
npm ERR! npm  v4.3.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! keytar@3.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the keytar@3.0.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the keytar package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs keytar
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls keytar
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\AlexBondo\AppData\Roaming\npm-cache\_logs\2017-02-21T21_43_46_332Z-debug.log
```

After installing manually installing node-gyp and windows-build-tools globally it worked.

`npm install --global node-gyp`
`npm install --global --production windows-build-tools`

Are these to required or am I doing something wrong?

**Comment by 50Wliu** [comment]
From the looks of it your Python executable wasn't found: `Error: Can't find Python executable "C:\Users\AlexBondo\AppData\Local\Programs\Python\Python35-32\python.exe", you can set the PYTHON env variable.`.

**Comment by abondoa** [comment]
Tried executing "C:\Users\AlexBondo\AppData\Local\Programs\Python\Python35-32\python.exe" in terminal and it started python as expected - also before installing node-gyp and windows-build-tools. Sorry for not specifying that originally.

**Comment by 50Wliu** [comment]
Ok, and what if you use python2?  I believe node-gyp is only compatible with python 2.

**Comment by julianilsson** [comment]
I ran into the exact same issue and I'm using python 2.7.10. @abondoa did you find a solution to the problem?

**Comment by hardik-shah-28** [comment]
Hi @abondoa  I am facing following problem can you please help me out. initially it was showing python problem you mentioned above but I was able to solve that but then I am getting this error.



C:\sls-azure-example>npm install

> keytar@4.0.3 install C:\sls-azure-example\node_modules\keytar
> node-gyp rebuild


C:\sls-azure-example\node_modules\keytar>if not defined npm_config_node_gyp (node "C:\Users\hshah\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error
 MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK vers
ion in the project property pages or by right-clicking the solution and selecting "Retarget solution". [C:\sls-azure-ex
ample\node_modules\keytar\build\keytar.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\hshah\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\hshah\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\sls-azure-example\node_modules\keytar
gyp ERR! node -v v6.11.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN azure-nodejs@1.0.0 No repository field.
npm WARN azure-nodejs@1.0.0 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keytar@4.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the keytar@4.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hshah\AppData\Roaming\npm-cache\_logs\2017-06-14T21_29_54_143Z-debug.log

C:\sls-azure-example>npm install

> keytar@4.0.3 install C:\sls-azure-example\node_modules\keytar
> node-gyp rebuild


C:\sls-azure-example\node_modules\keytar>if not defined npm_config_node_gyp (node "C:\Users\hshah\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\sls-azure-example\node_modules\keytar\build\keytar.vcxproj(20,3): error MSB4019: The imported project "C:\Microsoft.
Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exist
s on disk.
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\hshah\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\hshah\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\sls-azure-example\node_modules\keytar
gyp ERR! node -v v6.11.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN azure-nodejs@1.0.0 No repository field.
npm WARN azure-nodejs@1.0.0 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keytar@4.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the keytar@4.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hshah\AppData\Roaming\npm-cache\_logs\2017-06-14T21_43_02_826Z-debug.log

**Comment by hardik-shah-28** [comment]
sorry it got printed twice

**Comment by abondoa** [comment]
@julianilsson @hardik-shah-28 did you guys try to install node-gyp and windows-build-tools globally?

```
npm install --global node-gyp
npm install --global --production windows-build-tools
```

At least that did the trick for me. If you are not on windows you might need something else than windows-build-tools, but have not tried myself.
