### ISSUE TITLE
The module build/Release/keytar.node was compiled against a different Node.js version

### ISSUE THREAD

**Issue by alexcroox** [atom/node-keytar#64]
I'm using with Electron, install install runs fine but when importing it with node I get:

```
The module '.../node_modules/keytar/build/Release/keytar.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 51. This version of Node.js requires
NODE_MODULE_VERSION 53. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
```

I tried `npm rebuild keytar` with no joy

**Comment by jgknott** [comment]
Having the same issue.

**Comment by shiftkey** [comment]
@alexcroox @gjknott does an `npm rebuild` fix the issue? If not, more information about your setup and steps to reproduce this is necessary...

**Comment by jgknott** [comment]
`npm rebuild` didn't work for me.

Here's the error I'm getting:
```
keytar.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 51. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at /Users/jknott/Dropbox (Personal)/dev/ottter/desktop/node_modules/keytar/lib/keytar.js:1:161
    at Object.<anonymous> (/project/node_modules/keytar/lib/keytar.js:55:2)
```

**Comment by shiftkey** [comment]
> I'm on node `6.10` and npm `4.2.0`

These seem recent enough. Any thoughts @BinaryMuse on why they might still be seeing this error?

**Comment by BinaryMuse** [comment]
Unless I'm mistaken, `npm rebuild` will just rebuild the module against *Node's* version, not Electron's. You'll need to use one of the methods [in the Using Native Node Modules documentation](https://electron.atom.io/docs/tutorial/using-native-node-modules/)

**Comment by alexcroox** [comment]
Mine is node `7.6.0` and npm `4.1.2`

**Comment by jgknott** [comment]
@BinaryMuse that solved it!  Thank you!
Steps for mac:
`npm install --save-dev electron-rebuild`
`./node_modules/.bin/electron-rebuild`
I got some errors, on some packages but the keytar worked fine and now i'm able to run the app.

**Comment by alexcroox** [comment]
Does this mean the dev environment needs to be setup on each target OS and the module rebuilt on each? Or does a rebuild once on Mac cover all OS's?

**Comment by shiftkey** [comment]
> Does this mean the dev environment needs to be setup on each target OS and the module rebuilt on each? 

@alexcroox yes, because the native toolchain is OS-dependent

**Comment by liowmei** [comment]
Hi, i am new in using the firmware and i encounter the problem as below : 
The module '\\?\C:\Users\user\.atom\packages\Pymakr\precompiles\serialport-win\build\Release\serialport.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 49. This version of Node.js requires
NODE_MODULE_VERSION 53. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).

May i know how can i fix it? Thanks

**Comment by CorentinGC** [comment]
@liowmei Read the comment of @BinaryMuse and @jgknott ;) 
I am using serialport too, and this worked like a charm !

**Comment by Arthaclarius** [comment]
delete node_module and run `npm i`

**Comment by massi67** [comment]
Can somebody send steps to resolve issue in Windows?

**Comment by Riz-waan** [comment]
@massi67 did you try what @Arthaclarius said?

**Comment by mohamedbrahimi** [comment]
the same issue !, please any suggestion

**Comment by BinaryMuse** [comment]
Hi, folks,

Please see [the comment that I posted earlier](https://github.com/atom/node-keytar/issues/64#issuecomment-301621222). You'll need to follow the instructions on the [Using Native Node Modules](https://electronjs.org/docs/tutorial/using-native-node-modules) page on the Electron site. I personally use and recommend the strategy described in [Installing modules and rebuilding for Electron](https://electronjs.org/docs/tutorial/using-native-node-modules#installing-modules-and-rebuilding-for-electron), which describes how to fix this problem with the [electron-rebuild](https://github.com/electron/electron-rebuild) package.

Since the original issue is solved, I'm going to lock this issue. If you have a different problem, or have tried the above steps and it doesn't work, then please create a new issue and we can work to resolve it separately.
