### ISSUE TITLE
Use keyctl instead of the gnome-keyring

### ISSUE THREAD

**Issue by rgbkrk** [atom/node-keytar#7]
In order to make this work across Linux distros, I highly suggest using the built in key management tools in the Linux kernel.

**Comment by ramSeraph** [comment]
I want to take up this issue. Anyone I can talk to regarding this?

**Comment by 50Wliu** [comment]
> Anyone I can talk to regarding this?

@zcbenz would probably be your best bet.

**Comment by jbdatko** [comment]
I looked into this a bit, and I don't think key's in the kernel keyring persist after reboot. It exposes a procfs, but all of the keyctl operations manipulate in-memory data structures as best as I can tell from reading the [docs](http://lxr.free-electrons.com/source/Documentation/security/keys.txt).

I am not an expert in this subsystem however.

**Comment by implausible** [comment]
I'm following up on @jbdatko, I also went through the documentation and did some experiments with keyctl. Keyctl is not designed to persist keys across reboots. Forewarning for anyone looking at the get_persistent methods in keyctl: I believe persistent means across sessions, but not across reboots.
