### ISSUE TITLE
Keytar with macOS Sierra '0-1' items on Keychain app

### ISSUE THREAD

**Issue by popod** [atom/node-keytar#70]
On macOS Sierra, by using Keytar, I got many '0-1' items in Keychain application..

<img width="1135" alt="capture d ecran 2017-08-03 a 14 26 07" src="https://user-images.githubusercontent.com/3807312/28921878-0a89cf4c-7858-11e7-864d-5212f4807d1d.png">

**Comment by shiftkey** [comment]
I'm not sure what to do with this, as I don't really have much to go on:

 - what version of `keytar` was involved?
 - how are you using `keytar`?
 - `keytar` uses the default keychain, by passing `NULL` to [`SecKeychainAddGenericPassword`](https://developer.apple.com/documentation/security/1398366-seckeychainaddgenericpassword?language=objc)

https://github.com/atom/node-keytar/blob/6672ed49fe37f0d6c09f16c902bdfa9c0a72acaa/src/keytar_mac.cc#L62-L69

Are you able to provide more information about the behaviour you are seeing than the screenshot?

**Comment by popod** [comment]
Hi,

Sorry for the poor informations. I think it was:

- `keytar` version: 4.0.x 
- I use keytar as explain in the doc to simply store and query one password.
- The issue appear on macOS Sierra, and I have not seen this on Mojave (my actual OS).

As nobody seems to have the same, I think we could close this?

**Comment by shiftkey** [comment]
@popod I'm not aware of any other reports like this. If it's not reproducible in High Sierra or Mojave I'm fine with closing this out.
