### ISSUE TITLE
keytar.node reported as "suspicious" by McAfee 

### ISSUE THREAD

**Issue by k5e** [atom/node-keytar#75]
Hi,

I just installed Atom 1.20 on Windows 10 (version 1607). Since then, keytar.node, which is part of the Atom Package Manager apm, is reported as suspicious by McAfee:

![McAfee_WTF](https://user-images.githubusercontent.com/606885/30382848-884207ca-98a0-11e7-95eb-abf1b67651f4.png)

Thus, apm won't run. It used to be no issue until the update.

**Comment by shiftkey** [comment]
This is something that needs to be reported to the anti-virus vendor as a false positive so they can update their definitions.

**Comment by Punple** [comment]
Same issue here, but with F-Secure Antivirus.

**Comment by k5e** [comment]
A few virus definition file updates later the issue is gone.
