### ISSUE TITLE
"The user name or passphrase you entered is not correct." on macOS

### ISSUE THREAD

**Issue by dhleong** [atom/node-keytar#76]
Interestingly, writing a password via `setPassword` seems to work just fine, but attempting to then read it back throws an Error with no stack, and the message:

    Error: The user name or passphrase you entered is not correct.

Running macOS Sierra 10.12.6. No prompts for a password or anything appeared; it just immediately throws that error.

Using the `security` cli command as with the `keychain` or `xkeychain` modules seems to work just fine.

**Comment by shiftkey** [comment]
@dhleong do you have the snippet for how you're invoking `setPassword` and then `getPassword` to trigger the failure (feel free to obscure the password field, obvs)? Maybe we're doing something with the `service` or `account` string in one code path that's not done in the other...

**Comment by dhleong** [comment]
Wow, thanks for the quick response!

I'm setting as an async function, like so:

```javascript
    async saveCredentials(credentials) {
        await keytar.setPassword(
            this.service, this.account,
            this._serialize(credentials)
        );
        return true;
    }
```

`_serialize()` here just `JSON.stringify()`s a JSON object.

Loading looks basically like:

```javascript
    async loadCredentials() {
        try {
            const serialized = await keytar.getPassword(
                this.service, this.account
            );

            return this._inflate(serialized);
```

(The try is a fallback to `node-keychain` right now).

**Comment by shiftkey** [comment]
@dhleong I think I've stumbled on the same issue over in Desktop (unable to retrieve the password where it was working fine previously) so I'm digging into that now.

**Comment by shiftkey** [comment]
@dhleong unfortunately my error is easier to explain - a stale account in the app without anything in the keychain, so it fails as expected.

**Comment by fujungao** [comment]
@dhleong Hi, I google "The user name or passphrase you entered is not correct." and see your post. I am totally new in GitHub and not really understand what this thread is talking about 😓. I could not log in to Desktop after upgraded to macOS High Sierra, every time I try, " The user name or passphrase you entered is not correct." just popped up. Do you have any idea what should I do for this? thank you very much!

**Comment by dhleong** [comment]
@fujungao This is not a general support forum for OSX, but a place to report bugs with a specific tool used in programming. You're probably better off taking your Mac to an Apple Store, or posting on the [Apple Support Community](https://discussions.apple.com/welcome).

**Comment by yassermog** [comment]
I have this problem after I upgraded to macOS High Sierra

**Comment by mazzzai** [comment]
The same problem in HSierra. Any solutions?

**Comment by shiftkey** [comment]
One thing to look at is the Keychain itself - we had some reports of this in GitHub Desktop, and were somehow able [to workaround it](https://github.com/desktop/desktop/issues/3263#issuecomment-344590213):

> Try opening Keychain Access.app. Right-click on the `login` keychain and try locking it and then unlocking it again.

**Comment by mfardig** [comment]
Thanks @shiftkey - just lost about an hour trying to sort this out after updating to High Sierra.  After locking/unlocking in Keychain, works great!!! Thank you again, you are awesome!!!

**Comment by hgoshko** [comment]
@shiftkey hero of the day! (for me MySQLWorkbench failed to change db password after update to High Sierra)

**Comment by shiftkey** [comment]
I'm going to close this out as I continue to see reports of this being resolved in Keychain itself and it doesn't seem to be something we can control in `keytar`.
