### ISSUE TITLE
dev mode where async calls are async on all platforms

### ISSUE THREAD

**Issue by bengotow** [atom/node-keytar#81]
Hey!

I encountered a bug today that was really tricky to narrow down and only happened on Windows. Basically, our code does this:

```js
keytar.setPassword('mailspring', 'password', 'bla')
emitter.emit('changed')

// separately...
emitter.on('changed', () => {
  // rebuild some things, fetch the password
  keytar.getPassword('mailspring', 'password')
}
```

Obviously, the problem here is that I wasn't calling `await keytar.setPassword` or waiting for the password to actually be saved. However, this code works fine on MacOS, where the keytar library is either synchronous or super fast (finishing before the call to keytar.getPassword was made, or handling them in order at any rate.)

It'd be great if keytar had a "dev mode" where calls to setPassword and getPassword were intentionally made slower to better reflect the worst-case-scenario (I believe Windows?) Then I could test this on Mac and know it wouldn't behave differently on Windows.

**Comment by shiftkey** [comment]
I don't have plans to see this land, but in the interim this could be baked into your application code, based on the environment you're running in:

```ts
const timeout = (timeout: number) => {
  return new Promise(resolve => {
    window.setTimeout(() => {
      resolve()
    }, timeout)
  })
}

async function setItem(key: string, login: string, value: string) {
  if (process.env.NODE_ENV !== 'production') {
    await timeout(3000)
  }
  return keytar.setPassword(key, login, value)
}

async function getItem(key: string, login: string) {
  if (process.env.NODE_ENV !== 'production') {
    await timeout(3000)
  }
  return keytar.getPassword(key, login)
}
```

**Comment by shiftkey** [comment]
I'm going to close this out because I don't have plans to support this. I don't believe there's any restrictions to someone building a wrapper like the one in the previous code snippet into their app if they wanted to test their app handles a slow get/set operation when using `keytar`...
