### ISSUE TITLE
cannot install keytar on Windows

### ISSUE THREAD

**Issue by mvarakin** [atom/node-keytar#82]
Hi

I can't install keytar module in windows 10.
I always got the following error

npm i -g keytar

keytar@4.0.5 install C:\Users\Михаил\AppData\Roaming\npm\node_modules\keytar
node-gyp rebuild

C:\Users\Михаил\AppData\Roaming\npm\node_modules\keytar>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Сборка проектов в этом решении по одному. Чтобы включить параллельную сборку, добавьте параметр "/m".
  main.cc
  keytar_win.cc
  async.cc
  win_delay_load_hook.cc
**C:\Users\Михаил\AppData\Roaming\npm\node_modules\keytar\node_modules\nan\nan.h(23): fatal error C10
83: Cannot open include file: 'node_version.h': No such file or directory (compiling source file ..
\src\main.cc) [C:\Users\Михаил\AppData\Roaming\npm\node_modules\keytar\build\keytar.vcxproj]**
C:\Users\Михаил\AppData\Roaming\npm\node_modules\keytar\node_modules\nan\nan.h(23): fatal error C10
83: Cannot open include file: 'node_version.h': No such file or directory (compiling source file ..
\src\async.cc) [C:\Users\Михаил\AppData\Roaming\npm\node_modules\keytar\build\keytar.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Михаил\AppData\Roaming\npm\node_modules\keytar
gyp ERR! node -v v6.11.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "-g" "keytar"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

**Comment by mvarakin** [comment]
Does anyone monitor the issues?

**Comment by shiftkey** [comment]
> C:\Users\Михаил\AppData\Roaming\npm\node_modules\keytar\node_modules\nan\nan.h(23): fatal error C1083: Cannot open include file: 'node_version.h': No such file or directory (compiling source file ..\src\main.cc) 

This feels like an `nan` wasn't able to find the right headers for your version of Node. A more recent example of this is #20921 which affected Node `10.2.0` and needed end users to upgrade to `10.2.1`. 

Currently we are mostly tracking Node LTS releases but working on `10.x` support, so I'd recommend testing with a more recent version of Node and seeing if you still have the same issue

**Comment by radreamer** [comment]
I experience the same issue on both nodejs versions `8.11.3` and `10.6.0` but with other files:
```
18-Jul-2018 13:02:51 | > keytar@4.2.1 install C:\Users\build\bamboo-agent-home\xml-data\build-dir\QX-QE-BE\node_modules\keytar
-- | --
18-Jul-2018 13:02:51 | > prebuild-install \|\| node-gyp rebuild
18-Jul-2018 13:02:51 |  
18-Jul-2018 13:02:52 | internal/modules/cjs/loader.js:583
18-Jul-2018 13:02:52 | throw err;
18-Jul-2018 13:02:52 | ^
18-Jul-2018 13:02:52 |  
18-Jul-2018 13:02:52 | Error: Cannot find module './index'
18-Jul-2018 13:02:52 | at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
18-Jul-2018 13:02:52 | at Function.Module._load (internal/modules/cjs/loader.js:507:25)
18-Jul-2018 13:02:52 | at Module.require (internal/modules/cjs/loader.js:637:17)
18-Jul-2018 13:02:52 | at require (internal/modules/cjs/helpers.js:20:18)
18-Jul-2018 13:02:52 | at Object.<anonymous> (C:\Users\build\bamboo-agent-home\xml-data\build-dir\QX-QE-BE\node_modules\.bin\rc:2:10)
18-Jul-2018 13:02:52 | at Module._compile (internal/modules/cjs/loader.js:689:30)
18-Jul-2018 13:02:52 | at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
18-Jul-2018 13:02:52 | at Module.load (internal/modules/cjs/loader.js:599:32)
18-Jul-2018 13:02:52 | at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
18-Jul-2018 13:02:52 | at Function.Module._load (internal/modules/cjs/loader.js:530:3)
18-Jul-2018 13:03:09 | Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
18-Jul-2018 13:03:15 | async.cc
18-Jul-2018 13:03:15 | main.cc
18-Jul-2018 13:03:17 | C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\crtdefs.h(10): fatal error C1083: Cannot open include file: 'corecrt.h': No such file or directory (compiling source file ..\src\async.cc) [C:\Users\build\bamboo-agent-home\xml-data\build-dir\QX-QE-BE\node_modules\keytar\build\keytar.vcxproj]
18-Jul-2018 13:03:17 | c:\users\build\.electron-gyp\iojs-2.0.5\deps\uv\include\uv-errno.h(25): fatal error C1083: Cannot open include file: 'errno.h': No such file or directory (compiling source file ..\src\main.cc) [C:\Users\build\bamboo-agent-home\xml-data\build-dir\QX-QE-BE\node_modules\keytar\build\keytar.vcxproj]
18-Jul-2018 13:03:17 | keytar_win.cc
18-Jul-2018 13:03:17 | win_delay_load_hook.cc
18-Jul-2018 13:03:18 | C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\crtdefs.h(10): fatal error C1083: Cannot open include file: 'corecrt.h': No such file or directory (compiling source file ..\src\keytar_win.cc) [C:\Users\build\bamboo-agent-home\xml-data\build-dir\QX-QE-BE\node_modules\keytar\build\keytar.vcxproj]
18-Jul-2018 13:03:18 | C:\Program Files (x86)\Windows Kits\8.1\Include\um\winnt.h(31): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file C:\Users\build\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.cc) [C:\Users\build\bamboo-agent-home\xml-data\build-dir\QX-QE-BE\node_modules\keytar\build\keytar.vcxproj]
18-Jul-2018 13:03:19 | gyp ERR! build error
18-Jul-2018 13:03:19 | gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
18-Jul-2018 13:03:19 | gyp ERR! stack     at ChildProcess.onExit (C:\Users\build\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
18-Jul-2018 13:03:19 | gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
18-Jul-2018 13:03:19 | gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
18-Jul-2018 13:03:19 | gyp ERR! System Windows_NT 6.1.7601
18-Jul-2018 13:03:19 | gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\build\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
18-Jul-2018 13:03:19 | gyp ERR! cwd C:\Users\build\bamboo-agent-home\xml-data\build-dir\QX-QE-BE\node_modules\keytar
18-Jul-2018 13:03:19 | gyp ERR! node -v v10.6.0
18-Jul-2018 13:03:19 | gyp ERR! node-gyp -v v3.6.2
18-Jul-2018 13:03:19 | gyp ERR! not ok
18-Jul-2018 13:03:19 | npm ERR! code ELIFECYCLE
18-Jul-2018 13:03:19 | npm ERR! errno 1
18-Jul-2018 13:03:19 | npm ERR! keytar@4.2.1 install: `prebuild-install \|\| node-gyp rebuild`
18-Jul-2018 13:03:19 | npm ERR! Exit status 1
```

**Comment by shiftkey** [comment]
> C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\crtdefs.h(10): fatal error C1083: Cannot open include file: 'corecrt.h': No such file or directory (compiling source file ..\src\keytar_win.cc) 

@mvarakin there's a missing header file that keytar needs to compile against. I think you're missing some dependency from Visual Studio, e.g: https://stackoverflow.com/a/43905001/1363815

**Comment by radreamer** [comment]
@shiftkey thank you! I have Visual Studio 2015 that's why the solution for me was:
run the `Microsoft Visual C++ Build Tools` installer and modify it by installing `Windows 8.1 SDK` and`Windows 10 SDK`
