### ISSUE TITLE
build error in window 10 after installed windows-build-tools

### ISSUE THREAD

**Issue by wangtao0101** [atom/node-keytar#83]
λ node -v
v8.8.1

$ C:\Users\zeroone\Desktop\redmine_tracker-master\node_modules\.bin\electron-rebuild
× Rebuild Failed

An unhandled error occurred inside electron-rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.8.1 | win32 | x64
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [ 'C:\\Users\\zeroone\\Desktop\\redmine_tracker-master\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\zeroone\\Desktop\\redmine_tracker-master\\node_modules\\keytar-prebuild\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\zeroone\\Desktop\\redmine_tracker-master\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\zeroone\\.electron-gyp\\.node-gyp\\iojs-1.7.6\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\zeroone\\.electron-gyp\\.node-gyp\\iojs-1.7.6',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\zeroone\\Desktop\\redmine_tracker-master\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\zeroone\\.electron-gyp\\.node-gyp\\iojs-1.7.6\\<(target_arch)\\iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\zeroone\\Desktop\\redmine_tracker-master\\node_modules\\keytar-prebuild',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\zeroone\\Desktop\\redmine_tracker-master\\node_modules\\keytar-prebuild\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
�ڴ˽��������һ������һ����Ŀ����Ҫ���ò������ɣ�����ӡ�/m�����ء�
  async.cc
  main.cc
  keytar_win.cc
  win_delay_load_hook.cc
C:\Users\zeroone\.electron-gyp\.node-gyp\iojs-1.7.6\x64\iojs.lib : fatal error LNK1106: �ļ���Ч���������: �޷����ҵ� 0x2704CE [C:\Users\zeroone\Desktop\redmine_tracker-master\node_modules\keytar-prebuild\build\keytar.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\zeroone\Desktop\redmine_tracker-master\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\zeroone\\Desktop\\redmine_tracker-master\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=1.7.6" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source"
gyp ERR! cwd C:\Users\zeroone\Desktop\redmine_tracker-master\node_modules\keytar-prebuild
gyp ERR! node -v v8.8.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

Failed with exit code: 1

Error: gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.8.1 | win32 | x64
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [ 'C:\\Users\\zeroone\\Desktop\\redmine_tracker-master\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\zeroone\\Desktop\\redmine_tracker-master\\node_modules\\keytar-prebuild\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\zeroone\\Desktop\\redmine_tracker-master\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\zeroone\\.electron-gyp\\.node-gyp\\iojs-1.7.6\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\zeroone\\.electron-gyp\\.node-gyp\\iojs-1.7.6',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\zeroone\\Desktop\\redmine_tracker-master\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\zeroone\\.electron-gyp\\.node-gyp\\iojs-1.7.6\\<(target_arch)\\iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\zeroone\\Desktop\\redmine_tracker-master\\node_modules\\keytar-prebuild',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\zeroone\\Desktop\\redmine_tracker-master\\node_modules\\keytar-prebuild\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
�ڴ˽��������һ������һ����Ŀ����Ҫ���ò������ɣ�����ӡ�/m�����ء�
  async.cc
  main.cc
  keytar_win.cc
  win_delay_load_hook.cc
C:\Users\zeroone\.electron-gyp\.node-gyp\iojs-1.7.6\x64\iojs.lib : fatal error LNK1106: �ļ���Ч���������: �޷����ҵ� 0x2704CE [C:\Users\zeroone\Desktop\redmine_tracker-master\node_modules\keytar-prebuild\build\keytar.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\zeroone\Desktop\redmine_tracker-master\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\zeroone\\Desktop\\redmine_tracker-master\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=1.7.6" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source"
gyp ERR! cwd C:\Users\zeroone\Desktop\redmine_tracker-master\node_modules\keytar-prebuild
gyp ERR! node -v v8.8.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

Failed with exit code: 1
    at SafeSubscriber._error (C:\Users\zeroone\Desktop\redmine_tracker-master\node_modules\spawn-rx\lib\src\index.js:277:84)
    at SafeSubscriber.__tryOrUnsub (C:\Users\zeroone\Desktop\redmine_tracker-master\node_modules\rxjs\Subscriber.js:238:16)
    at SafeSubscriber.error (C:\Users\zeroone\Desktop\redmine_tracker-master\node_modules\rxjs\Subscriber.js:197:26)
    at Subscriber._error (C:\Users\zeroone\Desktop\redmine_tracker-master\node_modules\rxjs\Subscriber.js:128:26)
    at Subscriber.error (C:\Users\zeroone\Desktop\redmine_tracker-master\node_modules\rxjs\Subscriber.js:102:18)
    at MapSubscriber.Subscriber._error (C:\Users\zeroone\Desktop\redmine_tracker-master\node_modules\rxjs\Subscriber.js:128:26)
    at MapSubscriber.Subscriber.error (C:\Users\zeroone\Desktop\redmine_tracker-master\node_modules\rxjs\Subscriber.js:102:18)
    at SafeSubscriber._next (C:\Users\zeroone\Desktop\redmine_tracker-master\node_modules\spawn-rx\lib\src\index.js:251:65)
    at SafeSubscriber.__tryOrUnsub (C:\Users\zeroone\Desktop\redmine_tracker-master\node_modules\rxjs\Subscriber.js:238:16)
    at SafeSubscriber.next (C:\Users\zeroone\Desktop\redmine_tracker-master\node_modules\rxjs\Subscriber.js:185:22)

**Comment by shiftkey** [comment]
> `fatal error LNK1106: �ļ���Ч���������: �޷����ҵ� 0x2704CE [C:\Users\zeroone\Desktop\redmine_tracker-master\node_modules\keytar-prebuild\build\keytar.vcxproj]`

It's hard say what the rest of this error message is about but [LNK1106](
https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-error-lnk1106?view=vs-2019) suggests something isn't correct with the machine setup:

 - Disk full.
 - Trying to link over a network.
 - Bad block on your disk.
 - Out of heap space.
