### ISSUE TITLE
findPassword - incorrect documentation

### ISSUE THREAD

**Issue by Rob--W** [atom/node-keytar#87]
From https://github.com/atom/node-keytar/blob/0e1757ae895f63ece9c8641e112b892cbdff34cf/README.md#findpasswordservice :

> ### findPassword(service)
>
> Find a password for the `service` in the keychain.
>
>`service` - The string service name.
>
>Yields the string password, or `null` if an entry for the given service and account was not found.

Which given account? This docs looks like a copy-paste error from the `getPassword` method.
#36 questioned before why this function was needed, and although it has been closed, the question is still open - what is the purpose of `findPassword` ?

**Comment by shiftkey** [comment]
I think this is just a convenience function for situations where you don't need the `account` value. I'm going to tidy this up in #150. If that's not enough, maybe we can talk about deprecating it.
