### ISSUE TITLE
can't get password on ubuntu 16.04

### ISSUE THREAD

**Issue by skygragon** [atom/node-keytar#90]
here is the script to get chrome saved password key:
```
require('keytar').findCredentials('Chrome Safe Storage').then(console.log);
```
it works on macos to print the result, but always gives empty array on ubuntu?

ubuntu: 16.04.3
chrome: 63.0.3239.108

**Comment by shiftkey** [comment]
On Linux `keytar` uses `libsecret` APIs, which is a different implementation to macOS. I'm not sure Chrome on Ubuntu uses `libsecret` to store it's credentials, but that's mostly because I haven't [looked inside Chromium](https://cs.chromium.org/) to figure out what it's doing

**Comment by shiftkey** [comment]
Closing this out because it's not clear whether there are some platform-specific differences with how Chrome manages it's passwords on Linux.
