### ISSUE TITLE
npm install fails: package libsecret-1 was not found in the pkg-config search

### ISSUE THREAD

**Issue by cevhyruz** [atom/node-keytar#93]
- OS Version: Linux x64 4.14.0-kali1-amd64
---
I already run an installation  `sudo apt-get install libsecret-1-dev` as stated in the README.md yet npm install fails.. any idea? Thanks..

` $ npm install keytar `

keytar@4.1.0 install /home/devs/Projects/keytar-test/node_modules/keytar
 node-gyp rebuild

Package libsecret-1 was not found in the pkg-config searchpath.
Perhaps you should add the directory containing 'libsecret-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libsecret-1' found
gyp: Call to 'pkg-config --libs-only-l libsecret-1' returned exit status 1 while in binding.gyp. while trying to loadbinding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/devs/.linuxbrew/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 4.14.0-kali1-amd64
gyp ERR! command "/home/devs/.linuxbrew/Cellar/node/9.3.0_1/bin/node" "/home/devs/.linuxbrew/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/devs/Projects/keytar-test/node_modules/keytar
gyp ERR! node -v v9.3.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN keytar-test@1.0.0 No description
npm WARN keytar-test@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keytar@4.1.0 install: 'node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the keytar@4.1.0 install script.
npm ERR! This is probably not a problem with npm. There islikely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/devs/.npm/_logs/2018-01-08T07_04_38_424Z-debug.log

**Comment by abizake** [comment]
Any udpates on this . This issue is really a blocker and creating problems in deliveries.

**Comment by shiftkey** [comment]
@abizake I had a look at the contents of [`libsecret-1-dev`](https://packages.ubuntu.com/cosmic/amd64/libsecret-1-dev/filelist) to confirm it contains `libsecret-1.pc` so I guess maybe something with your `PKG_CONFIG_PATH` environment variable might not be set correctly?

It's essentially expecting this to resolve to `/usr/lib/x86_64-linux-gnu/pkgconfig/` but I'm not sure about your setup.

**Comment by shiftkey** [comment]
Closing this out due to inactivity and lack of information about the setup, and this suggestion seems the best thing to try first:

```
Perhaps you should add the directory containing 'libsecret-1.pc'
to the PKG_CONFIG_PATH environment variable
```
