### ISSUE TITLE
Unexpected E character in set password

### ISSUE THREAD

**Issue by Siocki** [atom/node-keytar#96]
When I am using setPassword method it gives me unexpeced E in the end of password (only if it contains numbers, for example password: beta09ve). I am using Windows 8.1 (same problem exists with Windows 10, it does not on osx though) and created the project using Electron Forge.

**Comment by KrzysZG37** [comment]
@Siocki , i got the same problem. Unfortunately i haven't found the solution yet.

**Comment by Siocki** [comment]
I checked the problem thoroughly, and password is set correctly, but method findCredentials returns passwords with character E in the end, when those passwords have number in it.

**Comment by cryppadotta** [comment]
I have the exact same problem, but it adds a `D` character at the end

**Comment by cryppadotta** [comment]
Interestingly enough, I only receive the incorrect extra character when I use `.findCredentials` -- If I use `getPassword` the value is returned correctly.

In the tests, unicode support is only tested by using `setPassword`/`getPassword` [see here](https://github.com/atom/node-keytar/blob/master/spec/keytar-spec.js#L44). It looks like someone needs to write a unicode-based test for `.findCredentials`, too.

**Comment by dracan** [comment]
I'm getting the same. Thanks for the fix @cryppadotta - do you know when this will go into a release?
